In [2]:
import pandas as pd

In [3]:
groundwater = pd.read_csv(
    "../raw/state-ground-water-level-information.csv"
)
dim_state = pd.read_csv(
    "../clean/dim_state.csv"
)
print(groundwater.shape)
print(groundwater.columns.tolist())
print(groundwater.head(10).to_string(index=False))
print("\nData types:")
print(groundwater.dtypes)
print("\nMissing values:")
print(groundwater.isna().sum())

(29, 4)
['State', 'Total Number of Monitored Stations', 'Observed Range of Water Level-min', 'Observed Range of Water Level-max']
            State  Total Number of Monitored Stations  Observed Range of Water Level-min  Observed Range of Water Level-max
   Andhra Pradesh                                 280                             -98.46                             203.54
Arunachal Pradesh                                   4                              -4.19                              -0.52
            Assam                                  68                             -89.66                              30.73
            Bihar                                  22                             -20.98                            1806.51
       Chandigarh                                  19                             -95.15                              73.46
     Chhattisgarh                                 243                            -940.98                              35.03
            Delhi                                  89                           -1000.00                              44.25
              Goa                                  39                             -29.26                               3.23
          Gujarat                                 407                            -231.45                           25423.53
          Haryana                                 207                           -1000.00                             100.12

Data types:
State                                     str
Total Number of Monitored Stations      int64
Observed Range of Water Level-min     float64
Observed Range of Water Level-max     float64
dtype: object

Missing values:
State                                 0
Total Number of Monitored Stations    0
Observed Range of Water Level-min     0
Observed Range of Water Level-max     0
dtype: int64

In [4]:
gw_states = set(groundwater["State"].str.strip())
dim_states = set(dim_state["state_name"].str.strip())

print("Missing from groundwater:")
print(sorted(dim_states - gw_states))

print("\nExtra in groundwater:")
print(sorted(gw_states - dim_states))

Missing from groundwater:
['Andaman and Nicobar Islands', 'Dadra and Nagar Haveli and Daman and Diu', 'Jammu and Kashmir', 'Ladakh', 'Lakshadweep', 'Manipur', 'Mizoram', 'Sikkim']

Extra in groundwater:
['Jammu & Kashmir']

In [5]:
from pathlib import Path

PDF_PATH = Path("../raw/Pre-monsoon_WL_1994-2025.pdf")

print("Exists:", PDF_PATH.exists())
print("Path:", PDF_PATH)

Exists: True
Path: ..\raw\Pre-monsoon_WL_1994-2025.pdf

In [6]:
import os

size_gb = os.path.getsize(PDF_PATH) / (1024 ** 3)

print(f"PDF size: {size_gb:.2f} GB")

PDF size: 0.09 GB

In [7]:
import pdfplumber

with pdfplumber.open(PDF_PATH) as pdf:
    page = pdf.pages[0]

    print("Page size:", page.width, "x", page.height)

    text = page.extract_text()
    print(text)

Page size: 841.92004 x 595.32001
Pre-monsoon Depth to Ground Water Level Data (in mbgl) for Unconfined Aquifer
State District Block Village Latitute Longitude Date WL(mbgl)
Andaman And Nicobar Islands North And Middle Andaman Diglipur Durgapur 13.27653 93.02364 30-04-25 0.46
Andaman And Nicobar Islands North And Middle Andaman Diglipur Keralapuram 13.2588 93.01351 30-04-25 1.31
Andaman And Nicobar Islands North And Middle Andaman Diglipur Kishorinagar (Parangara) 13.16506 92.88164 30-04-25 2.21
Andaman And Nicobar Islands North And Middle Andaman Diglipur Laxmipur 13.28734 92.96404 30-04-25 1.46
Andaman And Nicobar Islands North And Middle Andaman Diglipur Milangram 13.31475 92.94309 30-04-25 1.01
Andaman And Nicobar Islands North And Middle Andaman Diglipur Mohanpur 12.95448 92.83567 30-04-25 1.44
Andaman And Nicobar Islands North And Middle Andaman Diglipur Nabagram 13.15474 92.94847 30-04-25 0.55
Andaman And Nicobar Islands North And Middle Andaman Diglipur Rest Camp 12.8328 92.85923 30-04-25 0.49
Andaman And Nicobar Islands North And Middle Andaman Diglipur Shibpur 13.24783 93.04183 30-04-25 0.14
Andaman And Nicobar Islands North And Middle Andaman Diglipur Sitanagar 13.2261 92.93593 30-04-25 0.32
Andaman And Nicobar Islands North And Middle Andaman Diglipur Srinagar 13.13952 92.86818 30-04-25 1.66
Andaman And Nicobar Islands North And Middle Andaman Diglipur Subhasgram 13.24321 92.96616 30-04-25 0.42
Andaman And Nicobar Islands North And Middle Andaman Mayabunder Basantipur 12.75762 92.87271 30-04-25 0.48
Andaman And Nicobar Islands North And Middle Andaman Mayabunder Dhobidera (Mayabunder) 12.90988 92.89917 30-04-25 1.03
Andaman And Nicobar Islands North And Middle Andaman Mayabunder Haribay 13.00244 92.84416 30-04-25 2.42
Andaman And Nicobar Islands North And Middle Andaman Mayabunder Joypur 12.69862 92.88094 30-04-25 0.78
Andaman And Nicobar Islands North And Middle Andaman Mayabunder Pahalgaon 12.83941 92.85333 30-04-25 1.93
Andaman And Nicobar Islands North And Middle Andaman Mayabunder Swadeshnagar 12.6508 92.89132 30-04-25 0.64
Andaman And Nicobar Islands North And Middle Andaman Mayabunder Tugapur No. 8 12.81987 92.82236 30-04-25 0.3
Andaman And Nicobar Islands North And Middle Andaman Mayabunder Webi (Debipur) 12.86698 92.87201 30-04-25 0.53
Andaman And Nicobar Islands North And Middle Andaman Rangat Bakultala 12.50435 92.8584 30-04-25 0.68
Andaman And Nicobar Islands North And Middle Andaman Rangat Baratang (Nilambur) 12.16826 92.76692 30-04-25 1.02
Andaman And Nicobar Islands North And Middle Andaman Rangat Betapur 12.61899 92.94337 30-04-25 0.64
Andaman And Nicobar Islands North And Middle Andaman Rangat Kadamtala 12.34875 92.77499 30-04-25 0.72
Andaman And Nicobar Islands North And Middle Andaman Rangat Kausalyanagar 12.52906 92.81889 30-04-25 0.92
Andaman And Nicobar Islands North And Middle Andaman Rangat Long Island 12.36512 92.92463 30-04-25 2.07
Andaman And Nicobar Islands North And Middle Andaman Rangat Long Island 12.36463 92.92345 30-04-25 1.75
Andaman And Nicobar Islands North And Middle Andaman Rangat Long Island (Forest Area) 12.36674 92.92287 30-04-25 2.93
Andaman And Nicobar Islands North And Middle Andaman Rangat Long Island (Secon.School 12.33615 92.91972 30-04-25 2.03
Andaman And Nicobar Islands North And Middle Andaman Rangat Nimbutala 12.49457 92.95415 30-04-25 1.13
Andaman And Nicobar Islands North And Middle Andaman Rangat Padmanavapuram 12.60674 92.94929 30-04-25 4
Andaman And Nicobar Islands North And Middle Andaman Rangat Parnashala 12.52402 92.90421 30-04-25 0.15
Andaman And Nicobar Islands North And Middle Andaman Rangat Phooltala Basti 12.41168 92.76257 30-04-25 0.54
Andaman And Nicobar Islands North And Middle Andaman Rangat Porlobjig5 12.49577 92.78138 30-04-25 1.93
Andaman And Nicobar Islands North And Middle Andaman Rangat Rangat 12.50569 92.91168 30-04-25 0.43
Andaman And Nicobar Islands North And Middle Andaman Rangat South Creek (Sundergarh) 12.18682 92.79187 30-04-25 1.98
Andaman And Nicobar Islands North And Middle Andaman Rangat Tikadera 12.5227 92.81389 30-04-25 2.34
Andaman And Nicobar Islands North And Middle Andaman Rangat Uttara 12.3281 92.79002 30-04-25 0.27
Andaman And Nicobar Islands South Andamans Ferrargunj Annikat 11.70854 92.65007 30-04-25 1.56
Andaman And Nicobar Islands South Andamans Ferrargunj Bindraban 11.72186 92.66721 30-04-25 1.27
Andaman And Nicobar Islands South Andamans Ferrargunj Burmanala 11.55795 92.72935 30-04-25 0.92
Andaman And Nicobar Islands South Andamans Ferrargunj Chouldari 1 11.63123 92.66697 30-04-25 1.65
Andaman And Nicobar Islands South Andamans Ferrargunj Dhannikhari 11.61261 92.66714 30-04-25 1.21
Andaman And Nicobar Islands South Andamans Ferrargunj Ferrarganj 11.7171 92.65288 30-04-25 1.05
Andaman And Nicobar Islands South Andamans Ferrargunj Garacharma 11.61141 92.70261 30-04-25 1.11
Andaman And Nicobar Islands South Andamans Ferrargunj Gupta Para 11.55984 92.65864 30-04-25 1.12
Andaman And Nicobar Islands South Andamans Ferrargunj Hasmatabad 11.59472 92.64528 30-04-25 0.98
Andaman And Nicobar Islands South Andamans Ferrargunj Herbertabad 11.70819 92.61514 30-04-25 0.64
Andaman And Nicobar Islands South Andamans Ferrargunj Hope Town (Maremon Temple) 11.69805 92.72709 30-04-25 1.24
Andaman And Nicobar Islands South Andamans Ferrargunj Knoppuram 11.73719 92.70684 30-04-25 0.06
Andaman And Nicobar Islands South Andamans Ferrargunj Mamyo 11.53755 92.64795 30-04-25 1.46
Andaman And Nicobar Islands South Andamans Ferrargunj Manglutan 11.57166 92.66034 30-04-25 0.95

In [8]:
with pdfplumber.open(PDF_PATH) as pdf:
    page = pdf.pages[0]

    tables = page.extract_tables()

    print("Number of tables:", len(tables))

    if tables:
        table = tables[0]

        print("Number of rows:", len(table))
        print("Number of columns:", len(table[0]))

        for row in table[:10]:
            print(row)

Number of tables: 0

In [9]:
with pdfplumber.open(PDF_PATH) as pdf:
    page = pdf.pages[0]

    words = page.extract_words()

    for word in words[:80]:
        print(
            f"{word['text']:<30} "
            f"x0={word['x0']:.1f} "
            f"x1={word['x1']:.1f} "
            f"top={word['top']:.1f}"
        )

Pre-monsoon                    x0=274.8 x1=321.9 top=20.3
Depth                          x0=323.8 x1=345.3 top=20.3
to                             x0=347.3 x1=354.7 top=20.3
Ground                         x0=356.6 x1=383.2 top=20.3
Water                          x0=385.2 x1=407.0 top=20.3
Level                          x0=408.9 x1=427.0 top=20.3
Data                           x0=428.9 x1=445.4 top=20.3
(in                            x0=447.3 x1=456.5 top=20.3
mbgl)                          x0=458.6 x1=478.5 top=20.3
for                            x0=480.5 x1=490.7 top=20.3
Unconfined                     x0=492.5 x1=533.2 top=20.3
Aquifer                        x0=535.1 x1=561.2 top=20.3
State                          x0=20.2 x1=38.3 top=30.7
District                       x0=184.0 x1=209.0 top=30.7
Block                          x0=332.9 x1=351.7 top=30.7
Village                        x0=505.4 x1=528.9 top=30.7
Latitute                       x0=650.3 x1=677.5 top=30.7
Longitude                      x0=692.2 x1=727.1 top=30.7
Date                           x0=740.9 x1=757.5 top=30.7
WL(mbgl)                       x0=781.2 x1=815.0 top=30.7
Andaman                        x0=20.2 x1=53.2 top=41.0
And                            x0=55.2 x1=68.9 top=41.0
Nicobar                        x0=70.9 x1=97.7 top=41.0
Islands                        x0=99.6 x1=123.1 top=41.0
North                          x0=184.0 x1=203.9 top=41.0
And                            x0=205.8 x1=219.6 top=41.0
Middle                         x0=221.5 x1=245.6 top=41.0
Andaman                        x0=247.5 x1=280.6 top=41.0
Diglipur                       x0=332.9 x1=359.5 top=41.0
Durgapur                       x0=505.4 x1=537.7 top=41.0
13.27653                       x0=650.3 x1=681.9 top=41.0
93.02364                       x0=692.2 x1=723.8 top=41.0
30-04-25                       x0=740.9 x1=771.2 top=41.0
0.46                           x0=800.3 x1=815.1 top=41.0
Andaman                        x0=20.2 x1=53.2 top=51.3
And                            x0=55.2 x1=68.9 top=51.3
Nicobar                        x0=70.9 x1=97.7 top=51.3
Islands                        x0=99.6 x1=123.1 top=51.3
North                          x0=184.0 x1=203.9 top=51.3
And                            x0=205.8 x1=219.6 top=51.3
Middle                         x0=221.5 x1=245.6 top=51.3
Andaman                        x0=247.5 x1=280.6 top=51.3
Diglipur                       x0=332.9 x1=359.5 top=51.3
Keralapuram                    x0=505.4 x1=549.5 top=51.3
13.2588                        x0=650.3 x1=677.7 top=51.3
93.01351                       x0=692.2 x1=723.8 top=51.3
30-04-25                       x0=740.9 x1=771.2 top=51.3
1.31                           x0=800.3 x1=815.1 top=51.3
Andaman                        x0=20.2 x1=53.2 top=61.7
And                            x0=55.2 x1=68.9 top=61.7
Nicobar                        x0=70.9 x1=97.7 top=61.7
Islands                        x0=99.6 x1=123.1 top=61.7
North                          x0=184.0 x1=203.9 top=61.7
And                            x0=205.8 x1=219.6 top=61.7
Middle                         x0=221.5 x1=245.6 top=61.7
Andaman                        x0=247.5 x1=280.6 top=61.7
Diglipur                       x0=332.9 x1=359.5 top=61.7
Kishorinagar                   x0=505.4 x1=548.1 top=61.7
(Parangara)                    x0=549.9 x1=589.9 top=61.7
13.16506                       x0=650.3 x1=681.9 top=61.7
92.88164                       x0=692.2 x1=723.8 top=61.7
30-04-25                       x0=740.9 x1=771.2 top=61.7
2.21                           x0=800.3 x1=815.1 top=61.7
Andaman                        x0=20.2 x1=53.2 top=72.0
And                            x0=55.2 x1=68.9 top=72.0
Nicobar                        x0=70.9 x1=97.7 top=72.0
Islands                        x0=99.6 x1=123.1 top=72.0
North                          x0=184.0 x1=203.9 top=72.0
And                            x0=205.8 x1=219.6 top=72.0
Middle                         x0=221.5 x1=245.6 top=72.0
Andaman                        x0=247.5 x1=280.6 top=72.0
Diglipur                       x0=332.9 x1=359.5 top=72.0
Laxmipur                       x0=505.4 x1=537.0 top=72.0
13.28734                       x0=650.3 x1=681.9 top=72.0
92.96404                       x0=692.2 x1=723.8 top=72.0
30-04-25                       x0=740.9 x1=771.2 top=72.0
1.46                           x0=800.3 x1=815.1 top=72.0
Andaman                        x0=20.2 x1=53.2 top=82.3
And                            x0=55.2 x1=68.9 top=82.3
Nicobar                        x0=70.9 x1=97.7 top=82.3

In [10]:
import pdfplumber
import pandas as pd
import re


def extract_page(page):
    words = page.extract_words()

    # Group words by their vertical position.
    rows = {}

    for word in words:
        top = round(word["top"], 1)

        if top not in rows:
            rows[top] = []

        rows[top].append(word)

    extracted_rows = []

    for top, words_in_row in rows.items():

        # Sort words from left to right
        words_in_row = sorted(
            words_in_row,
            key=lambda x: x["x0"]
        )

        # Skip header/title rows
        if top <= 35:
            continue

        # Assign words to columns based on x-coordinate
        columns = {
            "State": [],
            "District": [],
            "Block": [],
            "Village": [],
            "Latitude": [],
            "Longitude": [],
            "Date": [],
            "WL_m_bgl": []
        }

        for word in words_in_row:
            x = word["x0"]
            text = word["text"]

            if 15 <= x < 150:
                columns["State"].append(text)

            elif 170 <= x < 315:
                columns["District"].append(text)

            elif 320 <= x < 490:
                columns["Block"].append(text)

            elif 495 <= x < 640:
                columns["Village"].append(text)

            elif 640 <= x < 688:
                columns["Latitude"].append(text)

            elif 688 <= x < 735:
                columns["Longitude"].append(text)

            elif 735 <= x < 790:
                columns["Date"].append(text)

            elif x >= 790:
                columns["WL_m_bgl"].append(text)

        row = {
            column: " ".join(values).strip()
            for column, values in columns.items()
        }

        # Only keep rows that look like actual observations
        if row["Latitude"] and row["Longitude"] and row["Date"]:
            extracted_rows.append(row)

    return pd.DataFrame(extracted_rows)

In [11]:
with pdfplumber.open(PDF_PATH) as pdf:
    page = pdf.pages[0]
    df_test = extract_page(page)

print(df_test.shape)
display(df_test.head(10))

(52, 8)

,State,District,Block,Village,Latitude,Longitude,Date,WL_m_bgl
0,Andaman And Nicobar Islands,North And Middle Andaman,Diglipur,Durgapur,13.27653,93.02364,30-04-25,0.46
1,Andaman And Nicobar Islands,North And Middle Andaman,Diglipur,Keralapuram,13.2588,93.01351,30-04-25,1.31
2,Andaman And Nicobar Islands,North And Middle Andaman,Diglipur,Kishorinagar (Parangara),13.16506,92.88164,30-04-25,2.21
3,Andaman And Nicobar Islands,North And Middle Andaman,Diglipur,Laxmipur,13.28734,92.96404,30-04-25,1.46
4,Andaman And Nicobar Islands,North And Middle Andaman,Diglipur,Milangram,13.31475,92.94309,30-04-25,1.01
5,Andaman And Nicobar Islands,North And Middle Andaman,Diglipur,Mohanpur,12.95448,92.83567,30-04-25,1.44
6,Andaman And Nicobar Islands,North And Middle Andaman,Diglipur,Nabagram,13.15474,92.94847,30-04-25,0.55
7,Andaman And Nicobar Islands,North And Middle Andaman,Diglipur,Rest Camp,12.8328,92.85923,30-04-25,0.49
8,Andaman And Nicobar Islands,North And Middle Andaman,Diglipur,Shibpur,13.24783,93.04183,30-04-25,0.14
9,Andaman And Nicobar Islands,North And Middle Andaman,Diglipur,Sitanagar,13.2261,92.93593,30-04-25,0.32

In [12]:
import pdfplumber
import pandas as pd

test_pages = []

with pdfplumber.open(PDF_PATH) as pdf:

    print("Total pages:", len(pdf.pages))

    for page_number in range(min(10, len(pdf.pages))):

        page = pdf.pages[page_number]

        page_df = extract_page(page)

        page_df["PDF_Page"] = page_number + 1

        test_pages.append(page_df)

df_10_pages = pd.concat(
    test_pages,
    ignore_index=True
)

print("Extracted rows:", len(df_10_pages))
print("Columns:", df_10_pages.columns.tolist())

display(df_10_pages.head())
display(df_10_pages.tail())

Total pages: 10270
Extracted rows: 520
Columns: ['State', 'District', 'Block', 'Village', 'Latitude', 'Longitude', 'Date', 'WL_m_bgl', 'PDF_Page']

,State,District,Block,Village,Latitude,Longitude,Date,WL_m_bgl,PDF_Page
0,Andaman And Nicobar Islands,North And Middle Andaman,Diglipur,Durgapur,13.27653,93.02364,30-04-25,0.46,1
1,Andaman And Nicobar Islands,North And Middle Andaman,Diglipur,Keralapuram,13.2588,93.01351,30-04-25,1.31,1
2,Andaman And Nicobar Islands,North And Middle Andaman,Diglipur,Kishorinagar (Parangara),13.16506,92.88164,30-04-25,2.21,1
3,Andaman And Nicobar Islands,North And Middle Andaman,Diglipur,Laxmipur,13.28734,92.96404,30-04-25,1.46,1
4,Andaman And Nicobar Islands,North And Middle Andaman,Diglipur,Milangram,13.31475,92.94309,30-04-25,1.01,1

,State,District,Block,Village,Latitude,Longitude,Date,WL_m_bgl,PDF_Page
515,Andhra Pradesh,Palnadu,Machavaram,Pillutla,16.5385,79.9057,25-05-25,2.45,10
516,Andhra Pradesh,Palnadu,Muppalla,Golapadu,16.3067,80.0833,25-05-25,3.07,10
517,Andhra Pradesh,Palnadu,Nadendla,Nadendla,16.1762,80.1843,22-05-25,9.81,10
518,Andhra Pradesh,Palnadu,Narasaraopeta,Jonnalagadda,16.2418,80.0829,22-05-25,2.88,10
519,Andhra Pradesh,Palnadu,Narasaraopeta,Lingamguntla,16.231,80.0318,22-05-25,6.41,10

In [14]:
import pdfplumber
import pandas as pd
from pathlib import Path
import time

OUTPUT_DIR = Path("../raw/groundwater")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

OUTPUT_FILE = OUTPUT_DIR / "pre_monsoon_1994_2025_raw.parquet"

CHUNK_SIZE = 100
buffer = []

start_time = time.time()

with pdfplumber.open(PDF_PATH) as pdf:

    total_pages = len(pdf.pages)

    print(f"Total pages: {total_pages}")

    for page_number, page in enumerate(pdf.pages, start=1):

        try:
            page_df = extract_page(page)

            if not page_df.empty:
                page_df["PDF_Page"] = page_number
                buffer.append(page_df)

        except Exception as e:
            print(f"ERROR on page {page_number}: {e}")

        # Save every CHUNK_SIZE pages
        if page_number % CHUNK_SIZE == 0:

            if buffer:
                chunk_df = pd.concat(
                    buffer,
                    ignore_index=True
                )

                chunk_file = (
                    OUTPUT_DIR /
                    f"pre_monsoon_pages_{page_number-CHUNK_SIZE+1}_{page_number}.parquet"
                )
                print(f"Saving pages : {page_number-CHUNK_SIZE+1} to {page_number} to {chunk_file}")
                chunk_df.to_parquet(
                    chunk_file,
                    index=False
                )

                buffer = []

            elapsed = time.time() - start_time

            print(
                f"Processed {page_number}/{total_pages} "
                f"pages | {elapsed/60:.1f} min"
            )

    # Save remaining pages
    if buffer:

        chunk_df = pd.concat(
            buffer,
            ignore_index=True
        )

        start_page = (
            total_pages // CHUNK_SIZE
        ) * CHUNK_SIZE + 1

        chunk_file = (
            OUTPUT_DIR /
            f"pre_monsoon_pages_{start_page}_{total_pages}.parquet"
        )

        chunk_df.to_parquet(
            chunk_file,
            index=False
        )

print("Extraction complete.")

Total pages: 10270
Saving pages : 1 to 100 to ..\raw\groundwater\pre_monsoon_pages_1_100.parquet
Processed 100/10270 pages | 0.6 min
Saving pages : 101 to 200 to ..\raw\groundwater\pre_monsoon_pages_101_200.parquet
Processed 200/10270 pages | 1.4 min
Saving pages : 201 to 300 to ..\raw\groundwater\pre_monsoon_pages_201_300.parquet
Processed 300/10270 pages | 2.1 min
Saving pages : 301 to 400 to ..\raw\groundwater\pre_monsoon_pages_301_400.parquet
Processed 400/10270 pages | 3.3 min
Processed 500/10270 pages | 3.9 min
Processed 600/10270 pages | 4.6 min
Processed 700/10270 pages | 5.1 min
Processed 800/10270 pages | 6.0 min
Processed 900/10270 pages | 6.3 min

KeyboardInterrupt:

In [ ]:
import pdfplumber
import pandas as pd
from pathlib import Path
import time

OUTPUT_DIR = Path("../raw/groundwater")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

OUTPUT_FILE = OUTPUT_DIR / "pre_monsoon_1994_2025_raw.parquet"

CHUNK_SIZE = 100
buffer = []
PDF_PATH = Path("../raw/August_WL_1994-2025.pdf")
start_time = time.time()

with pdfplumber.open(PDF_PATH) as pdf:

    total_pages = len(pdf.pages)

    print(f"Total pages: {total_pages}")

    for page_number, page in enumerate(pdf.pages, start=1):

        try:
            page_df = extract_page(page)

            if not page_df.empty:
                page_df["PDF_Page"] = page_number
                buffer.append(page_df)

        except Exception as e:
            print(f"ERROR on page {page_number}: {e}")

        # Save every CHUNK_SIZE pages
        if page_number % CHUNK_SIZE == 0:

            if buffer:
                chunk_df = pd.concat(
                    buffer,
                    ignore_index=True
                )

                chunk_file = (
                    OUTPUT_DIR /
                    f"pre_monsoon_pages_{page_number-CHUNK_SIZE+1}_{page_number}.parquet"
                )

                chunk_df.to_parquet(
                    chunk_file,
                    index=False
                )

                buffer = []

            elapsed = time.time() - start_time

            print(
                f"Processed {page_number}/{total_pages} "
                f"pages | {elapsed/60:.1f} min"
            )

    # Save remaining pages
    if buffer:

        chunk_df = pd.concat(
            buffer,
            ignore_index=True
        )

        start_page = (
            total_pages // CHUNK_SIZE
        ) * CHUNK_SIZE + 1

        chunk_file = (
            OUTPUT_DIR /
            f"pre_monsoon_pages_{start_page}_{total_pages}.parquet"
        )

        chunk_df.to_parquet(
            chunk_file,
            index=False
        )

print("Extraction complete.")

In [15]:
import pdfplumber
import pandas as pd

PDF_PATH = "../raw/Pre-monsoon_WL_1994-2025.pdf"

with pdfplumber.open(PDF_PATH) as pdf:

    page = pdf.pages[400]   # PDF page 401

    print("Page size:", page.width, "x", page.height)

    words = page.extract_words()

    print("\nNumber of words:", len(words))

    print("\nFirst 100 extracted words:")
    for w in words[:100]:
        print(
            f"x0={w['x0']:.2f}, "
            f"top={w['top']:.2f}, "
            f"text='{w['text']}'"
        )

Page size: 841.92004 x 595.32001

Number of words: 369

First 100 extracted words:
x0=224.76, top=20.73, text='Pre-monsoon'
x0=291.88, top=20.73, text='Depth'
x0=324.02, top=20.73, text='to'
x0=336.95, top=20.73, text='Ground'
x0=375.90, top=20.73, text='Water'
x0=408.44, top=20.73, text='Level'
x0=435.89, top=20.73, text='Data'
x0=461.04, top=20.73, text='(in'
x0=476.40, top=20.73, text='mbgl)'
x0=506.60, top=20.73, text='for'
x0=523.14, top=20.73, text='Unconfined'
x0=581.58, top=20.73, text='Aquifer'
x0=23.40, top=36.19, text='STATE_UT'
x0=183.50, top=36.19, text='DISTRICT'
x0=323.35, top=36.19, text='BLOCK'
x0=433.17, top=36.19, text='VILLAGE'
x0=572.18, top=36.19, text='LATITUDE'
x0=630.60, top=36.19, text='LONGITUDE'
x0=706.95, top=36.19, text='Date'
x0=762.48, top=36.07, text='WL'
x0=778.90, top=36.07, text='(in'
x0=792.84, top=36.07, text='mbgl)'
x0=23.40, top=50.11, text='Goa'
x0=183.48, top=50.11, text='South'
x0=210.71, top=50.11, text='Goa'
x0=323.40, top=50.11, text='Canacona'
x0=433.20, top=50.11, text='Sristal'
x0=581.64, top=50.11, text='14.99245'
x0=645.84, top=50.11, text='74.10557'
x0=704.64, top=50.23, text='10-05-24'
x0=798.96, top=50.11, text='11.4'
x0=23.40, top=64.03, text='Goa'
x0=183.48, top=64.03, text='South'
x0=210.71, top=64.03, text='Goa'
x0=323.40, top=64.03, text='Canacona'
x0=433.20, top=64.03, text='Yedda'
x0=581.64, top=64.03, text='14.99803'
x0=645.84, top=64.03, text='74.19071'
x0=704.64, top=64.15, text='10-05-24'
x0=804.36, top=64.03, text='5.0'
x0=23.40, top=77.95, text='Goa'
x0=183.48, top=77.95, text='South'
x0=210.71, top=77.95, text='Goa'
x0=323.40, top=77.95, text='Dharbandora'
x0=433.20, top=77.95, text='Bolkharnem'
x0=581.64, top=77.95, text='15.42964'
x0=645.84, top=77.95, text='74.19235'
x0=704.64, top=78.07, text='10-05-24'
x0=804.36, top=77.95, text='7.2'
x0=23.40, top=91.87, text='Goa'
x0=183.48, top=91.87, text='South'
x0=210.71, top=91.87, text='Goa'
x0=323.40, top=91.87, text='Dharbandora'
x0=433.20, top=91.87, text='Colem'
x0=581.64, top=91.87, text='15.33497'
x0=645.84, top=91.87, text='74.24375'
x0=704.64, top=91.99, text='10-05-24'
x0=804.36, top=91.87, text='8.5'
x0=23.40, top=105.79, text='Goa'
x0=183.48, top=105.79, text='South'
x0=210.71, top=105.79, text='Goa'
x0=323.40, top=105.79, text='Dharbandora'
x0=433.20, top=105.79, text='Darbandora'
x0=581.64, top=105.79, text='15.39284'
x0=645.84, top=105.79, text='74.12097'
x0=704.64, top=105.91, text='10-05-24'
x0=798.96, top=105.79, text='11.5'
x0=23.40, top=119.71, text='Goa'
x0=183.48, top=119.71, text='South'
x0=210.71, top=119.71, text='Goa'
x0=323.40, top=119.71, text='Dharbandora'
x0=433.20, top=119.71, text='Molem'
x0=581.64, top=119.71, text='15.36379'
x0=645.84, top=119.71, text='74.17534'
x0=704.64, top=119.83, text='10-05-24'
x0=804.36, top=119.71, text='5.8'
x0=23.40, top=133.63, text='Goa'
x0=183.48, top=133.63, text='South'
x0=210.71, top=133.63, text='Goa'
x0=323.40, top=133.63, text='Dharbandora'
x0=433.20, top=133.63, text='Molem'
x0=581.64, top=133.63, text='15.37701'
x0=645.84, top=133.63, text='74.22971'
x0=704.64, top=133.75, text='10-05-24'
x0=798.96, top=133.63, text='13.8'
x0=23.40, top=147.55, text='Goa'
x0=183.48, top=147.55, text='South'
x0=210.71, top=147.55, text='Goa'
x0=323.40, top=147.55, text='Mormugao'
x0=433.20, top=147.55, text='Bagmola'
x0=581.64, top=147.55, text='15.37006'
x0=645.84, top=147.55, text='73.83826'
x0=704.64, top=147.67, text='10-05-24'
x0=804.36, top=147.55, text='2.8'
x0=23.40, top=161.47, text='Goa'
x0=183.48, top=161.47, text='South'
x0=210.71, top=161.47, text='Goa'
x0=323.40, top=161.47, text='Mormugao'
x0=433.20, top=161.47, text='Chicalim'
x0=471.84, top=161.47, text='(Ct)'

In [16]:
import pdfplumber
import pandas as pd
import re

PDF_PATH = "../raw/Pre-monsoon_WL_1994-2025.pdf"


# ---------------------------------------------------------
# Header aliases
# ---------------------------------------------------------

HEADER_ALIASES = {
    "State": {
        "STATE",
        "STATE_UT",
        "STATE/UT",
        "STATE_UT_NAME"
    },

    "District": {
        "DISTRICT"
    },

    "Block": {
        "BLOCK"
    },

    "Village": {
        "VILLAGE"
    },

    "Latitude": {
        "LATITUDE",
        "LATITUTE"      # tolerate source typo
    },

    "Longitude": {
        "LONGITUDE",
        "LONGITUTE"
    },

    "Date": {
        "DATE"
    },

    "WL_m_bgl": {
        "WL",
        "WATERLEVEL",
        "WATER_LEVEL"
    }
}


# ---------------------------------------------------------
# Normalize text
# ---------------------------------------------------------

def normalize_header(text):

    text = text.upper().strip()

    # Remove punctuation / brackets
    text = re.sub(
        r"[^A-Z0-9_/]",
        "",
        text
    )

    return text


# ---------------------------------------------------------
# Detect header
# ---------------------------------------------------------

def detect_header(rows):

    for top, row_words in rows.items():

        row_words = sorted(
            row_words,
            key=lambda x: x["x0"]
        )

        detected = {}

        for word in row_words:

            normalized = normalize_header(
                word["text"]
            )

            for column, aliases in HEADER_ALIASES.items():

                if normalized in aliases:

                    detected[column] = word["x0"]

                    break

        # We need at least the important structural
        # columns to consider this a header.
        required = {
            "State",
            "District",
            "Block",
            "Village",
            "Latitude",
            "Longitude"
        }

        if required.issubset(detected):

            return top, detected

    return None, None


# ---------------------------------------------------------
# Extract page
# ---------------------------------------------------------

def extract_page(page):

    words = page.extract_words()

    if not words:
        return pd.DataFrame()

    # ---------------------------------------------
    # Group words by horizontal row
    # ---------------------------------------------

    rows = {}

    for word in words:

        top = round(
            word["top"],
            1
        )

        rows.setdefault(
            top,
            []
        ).append(word)

    # ---------------------------------------------
    # Detect header dynamically
    # ---------------------------------------------

    header_top, header_positions = detect_header(
        rows
    )

    if header_positions is None:

        print("Header not detected")

        return pd.DataFrame()

    # ---------------------------------------------
    # Order columns according to their position
    # ---------------------------------------------

    ordered_columns = sorted(
        header_positions.items(),
        key=lambda x: x[1]
    )

    # ---------------------------------------------
    # Create boundaries from midpoint
    # ---------------------------------------------

    boundaries = {}

    for i, (column, position) in enumerate(
        ordered_columns
    ):

        if i == 0:

            left = 0

        else:

            previous_position = (
                ordered_columns[i - 1][1]
            )

            left = (
                previous_position +
                position
            ) / 2

        if i == len(ordered_columns) - 1:

            right = page.width

        else:

            next_position = (
                ordered_columns[i + 1][1]
            )

            right = (
                position +
                next_position
            ) / 2

        boundaries[column] = (
            left,
            right
        )

    # ---------------------------------------------
    # Extract data rows
    # ---------------------------------------------

    extracted_rows = []

    for top, row_words in rows.items():

        # Ignore title and header
        if top <= header_top:

            continue

        row_words = sorted(
            row_words,
            key=lambda x: x["x0"]
        )

        row = {
            column: []
            for column in header_positions
        }

        for word in row_words:

            x = word["x0"]

            for column, (
                left,
                right
            ) in boundaries.items():

                if left <= x < right:

                    row[column].append(
                        word["text"]
                    )

                    break

        # -----------------------------------------
        # Join words
        # -----------------------------------------

        row = {
            column: " ".join(values).strip()
            for column, values in row.items()
        }

        # -----------------------------------------
        # Validate observation
        # -----------------------------------------

        if (
            row.get("Latitude")
            and row.get("Longitude")
            and row.get("Date")
        ):

            extracted_rows.append(row)

    return pd.DataFrame(
        extracted_rows
    )

In [18]:
import pdfplumber
import pandas as pd
import time
from pathlib import Path
import re


# =========================================================
# CONFIGURATION
# =========================================================

PDF_PATH = Path("../raw/Pre-monsoon_WL_1994-2025.pdf")

OUTPUT_DIR = Path(
    "../raw/groundwater/pre_monsoon_chunks"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

START_PAGE = 1
END_PAGE = 10270
CHUNK_SIZE = 100


# =========================================================
# HEADER ALIASES
# =========================================================

HEADER_ALIASES = {

    "State": {
        "STATE",
        "STATE_UT",
        "STATE/UT",
        "STATE_UT_NAME"
    },

    "District": {
        "DISTRICT"
    },

    "Block": {
        "BLOCK"
    },

    "Village": {
        "VILLAGE"
    },

    "Latitude": {
        "LATITUDE",
        "LATITUTE"
    },

    "Longitude": {
        "LONGITUDE",
        "LONGITUTE"
    },

    "Date": {
        "DATE"
    },

    "WL_m_bgl": {
        "WL",
        "WATERLEVEL",
        "WATER_LEVEL"
    }
}


# =========================================================
# NORMALIZE HEADER TEXT
# =========================================================

def normalize_header(text):

    text = text.upper().strip()

    text = re.sub(
        r"[^A-Z0-9_/]",
        "",
        text
    )

    return text


# =========================================================
# DETECT HEADER
# =========================================================

def detect_header(rows):

    for top, row_words in rows.items():

        row_words = sorted(
            row_words,
            key=lambda x: x["x0"]
        )

        detected = {}

        for word in row_words:

            normalized = normalize_header(
                word["text"]
            )

            for column, aliases in HEADER_ALIASES.items():

                if normalized in aliases:

                    detected[column] = word["x0"]

                    break

        required = {
            "State",
            "District",
            "Block",
            "Village",
            "Latitude",
            "Longitude"
        }

        if required.issubset(detected):

            return top, detected

    return None, None


# =========================================================
# EXTRACT ONE PAGE
# =========================================================

def extract_page(page):

    words = page.extract_words()

    if not words:
        return pd.DataFrame()

    # -----------------------------------------------------
    # Group words by vertical position
    # -----------------------------------------------------

    rows = {}

    for word in words:

        top = round(
            word["top"],
            1
        )

        rows.setdefault(
            top,
            []
        ).append(word)

    # -----------------------------------------------------
    # Detect table header
    # -----------------------------------------------------

    header_top, header_positions = detect_header(
        rows
    )

    if header_positions is None:

        return pd.DataFrame()

    # -----------------------------------------------------
    # Sort columns according to their x-position
    # -----------------------------------------------------

    ordered_columns = sorted(
        header_positions.items(),
        key=lambda x: x[1]
    )

    # -----------------------------------------------------
    # Calculate boundaries dynamically
    # -----------------------------------------------------

    boundaries = {}

    for i, (column, position) in enumerate(
        ordered_columns
    ):

        if i == 0:

            left = 0

        else:

            previous_position = (
                ordered_columns[i - 1][1]
            )

            left = (
                previous_position +
                position
            ) / 2

        if i == len(ordered_columns) - 1:

            right = page.width

        else:

            next_position = (
                ordered_columns[i + 1][1]
            )

            right = (
                position +
                next_position
            ) / 2

        boundaries[column] = (
            left,
            right
        )

    # -----------------------------------------------------
    # Extract rows
    # -----------------------------------------------------

    extracted_rows = []

    for top, row_words in rows.items():

        # Skip title/header
        if top <= header_top:
            continue

        row_words = sorted(
            row_words,
            key=lambda x: x["x0"]
        )

        row = {
            column: []
            for column in header_positions
        }

        for word in row_words:

            x = word["x0"]

            for column, (
                left,
                right
            ) in boundaries.items():

                if left <= x < right:

                    row[column].append(
                        word["text"]
                    )

                    break

        # -------------------------------------------------
        # Join words
        # -------------------------------------------------

        row = {
            column: " ".join(values).strip()
            for column, values in row.items()
        }

        # -------------------------------------------------
        # Validate observation
        # -------------------------------------------------

        if (
            row.get("Latitude")
            and row.get("Longitude")
            and row.get("Date")
            and row.get("WL_m_bgl")
        ):

            extracted_rows.append(row)

    return pd.DataFrame(
        extracted_rows
    )


# =========================================================
# FULL EXTRACTION
# =========================================================

start_time = time.time()

total_rows = 0
successful_pages = 0
failed_pages = []
empty_pages = []


with pdfplumber.open(PDF_PATH) as pdf:

    total_pdf_pages = len(pdf.pages)

    print(
        f"PDF pages available: "
        f"{total_pdf_pages:,}"
    )

    print(
        f"Pages to process: "
        f"{START_PAGE:,} → {END_PAGE:,}"
    )

    print(
        f"Chunk size: {CHUNK_SIZE}"
    )

    print(
        f"Output directory: "
        f"{OUTPUT_DIR}"
    )

    # -----------------------------------------------------
    # Process chunks
    # -----------------------------------------------------

    for chunk_start in range(
        START_PAGE,
        END_PAGE + 1,
        CHUNK_SIZE
    ):

        chunk_end = min(
            chunk_start + CHUNK_SIZE - 1,
            END_PAGE
        )

        print("\n" + "=" * 70)

        print(
            f"Processing pages "
            f"{chunk_start:,} → {chunk_end:,}"
        )

        print("=" * 70)

        chunk_rows = []

        chunk_start_time = time.time()

        # -------------------------------------------------
        # Process individual pages
        # -------------------------------------------------

        for page_number in range(
            chunk_start,
            chunk_end + 1
        ):

            try:

                page = pdf.pages[
                    page_number - 1
                ]

                page_df = extract_page(
                    page
                )

                if not page_df.empty:

                    page_df["PDF_Page"] = (
                        page_number
                    )

                    chunk_rows.append(
                        page_df
                    )

                    successful_pages += 1

                else:

                    empty_pages.append(
                        page_number
                    )

            except Exception as e:

                failed_pages.append(
                    (
                        page_number,
                        str(e)
                    )
                )

        # -------------------------------------------------
        # Save chunk
        # -------------------------------------------------

        if chunk_rows:

            chunk_df = pd.concat(
                chunk_rows,
                ignore_index=True
            )

            output_file = (
                OUTPUT_DIR /
                f"pre_monsoon_pages_"
                f"{chunk_start}_{chunk_end}.parquet"
            )

            chunk_df.to_parquet(
                output_file,
                index=False
            )

            chunk_rows_count = len(
                chunk_df
            )

            total_rows += (
                chunk_rows_count
            )

            chunk_time = (
                time.time()
                - chunk_start_time
            )

            print(
                f"✓ SAVED: "
                f"{output_file.name}"
            )

            print(
                f"  Rows: "
                f"{chunk_rows_count:,}"
            )

            print(
                f"  Time: "
                f"{chunk_time / 60:.2f} min"
            )

        else:

            print(
                f"⚠ No rows extracted "
                f"from {chunk_start}-{chunk_end}"
            )

        # -------------------------------------------------
        # Overall progress
        # -------------------------------------------------

        elapsed = (
            time.time()
            - start_time
        )

        progress = (
            chunk_end
            / END_PAGE
            * 100
        )

        print(
            f"Progress: "
            f"{chunk_end:,}/{END_PAGE:,} "
            f"({progress:.1f}%)"
        )

        print(
            f"Total rows so far: "
            f"{total_rows:,}"
        )

        print(
            f"Elapsed: "
            f"{elapsed / 60:.2f} minutes"
        )


# =========================================================
# FINAL SUMMARY
# =========================================================

total_time = (
    time.time()
    - start_time
)

print("\n")
print("=" * 70)
print("EXTRACTION COMPLETE")
print("=" * 70)

print(
    f"Pages processed: "
    f"{START_PAGE:,} → {END_PAGE:,}"
)

print(
    f"Successful pages: "
    f"{successful_pages:,}"
)

print(
    f"Empty pages: "
    f"{len(empty_pages):,}"
)

print(
    f"Failed pages: "
    f"{len(failed_pages):,}"
)

print(
    f"Total rows: "
    f"{total_rows:,}"
)

print(
    f"Total time: "
    f"{total_time / 60:.2f} minutes"
)

if failed_pages:

    print("\nFailed pages:")

    for page_number, error in failed_pages[:20]:

        print(
            page_number,
            error
        )

    if len(failed_pages) > 20:

        print(
            f"... and "
            f"{len(failed_pages) - 20} more"
        )

if empty_pages:

    print("\nFirst empty pages:")

    print(
        empty_pages[:30]
    )

PDF pages available: 10,270
Pages to process: 1 → 10,270
Chunk size: 100
Output directory: ..\raw\groundwater\pre_monsoon_chunks

======================================================================
Processing pages 1 → 100
======================================================================
⚠ No rows extracted from 1-100
Progress: 100/10,270 (1.0%)
Total rows so far: 0
Elapsed: 1.44 minutes

======================================================================
Processing pages 101 → 200
======================================================================
⚠ No rows extracted from 101-200
Progress: 200/10,270 (1.9%)
Total rows so far: 0
Elapsed: 2.53 minutes

======================================================================
Processing pages 201 → 300
======================================================================
⚠ No rows extracted from 201-300
Progress: 300/10,270 (2.9%)
Total rows so far: 0
Elapsed: 4.38 minutes

======================================================================
Processing pages 301 → 400
======================================================================
⚠ No rows extracted from 301-400
Progress: 400/10,270 (3.9%)
Total rows so far: 0
Elapsed: 5.36 minutes

======================================================================
Processing pages 401 → 500
======================================================================
⚠ No rows extracted from 401-500
Progress: 500/10,270 (4.9%)
Total rows so far: 0
Elapsed: 6.12 minutes

======================================================================
Processing pages 501 → 600
======================================================================
⚠ No rows extracted from 501-600
Progress: 600/10,270 (5.8%)
Total rows so far: 0
Elapsed: 7.21 minutes

======================================================================
Processing pages 601 → 700
======================================================================
⚠ No rows extracted from 601-700
Progress: 700/10,270 (6.8%)
Total rows so far: 0
Elapsed: 8.26 minutes

======================================================================
Processing pages 701 → 800
======================================================================
⚠ No rows extracted from 701-800
Progress: 800/10,270 (7.8%)
Total rows so far: 0
Elapsed: 9.09 minutes

======================================================================
Processing pages 801 → 900
======================================================================
⚠ No rows extracted from 801-900
Progress: 900/10,270 (8.8%)
Total rows so far: 0
Elapsed: 10.45 minutes

======================================================================
Processing pages 901 → 1,000
======================================================================

KeyboardInterrupt:

In [19]:
import pdfplumber

PDF_PATH = "../raw/Pre-monsoon_WL_1994-2025.pdf"

with pdfplumber.open(PDF_PATH) as pdf:

    page = pdf.pages[0]

    words = page.extract_words()

    rows = {}

    for word in words:

        top = round(word["top"], 1)

        rows.setdefault(top, []).append(word)

    print("Number of row groups:", len(rows))

    for top, row_words in list(rows.items())[:10]:

        row_words = sorted(
            row_words,
            key=lambda x: x["x0"]
        )

        print("\nTOP:", top)

        print(
            [
                word["text"]
                for word in row_words
            ]
        )

Number of row groups: 54

TOP: 20.3
['Pre-monsoon', 'Depth', 'to', 'Ground', 'Water', 'Level', 'Data', '(in', 'mbgl)', 'for', 'Unconfined', 'Aquifer']

TOP: 30.7
['State', 'District', 'Block', 'Village', 'Latitute', 'Longitude', 'Date', 'WL(mbgl)']

TOP: 41.0
['Andaman', 'And', 'Nicobar', 'Islands', 'North', 'And', 'Middle', 'Andaman', 'Diglipur', 'Durgapur', '13.27653', '93.02364', '30-04-25', '0.46']

TOP: 51.3
['Andaman', 'And', 'Nicobar', 'Islands', 'North', 'And', 'Middle', 'Andaman', 'Diglipur', 'Keralapuram', '13.2588', '93.01351', '30-04-25', '1.31']

TOP: 61.7
['Andaman', 'And', 'Nicobar', 'Islands', 'North', 'And', 'Middle', 'Andaman', 'Diglipur', 'Kishorinagar', '(Parangara)', '13.16506', '92.88164', '30-04-25', '2.21']

TOP: 72.0
['Andaman', 'And', 'Nicobar', 'Islands', 'North', 'And', 'Middle', 'Andaman', 'Diglipur', 'Laxmipur', '13.28734', '92.96404', '30-04-25', '1.46']

TOP: 82.3
['Andaman', 'And', 'Nicobar', 'Islands', 'North', 'And', 'Middle', 'Andaman', 'Diglipur', 'Milangram', '13.31475', '92.94309', '30-04-25', '1.01']

TOP: 92.6
['Andaman', 'And', 'Nicobar', 'Islands', 'North', 'And', 'Middle', 'Andaman', 'Diglipur', 'Mohanpur', '12.95448', '92.83567', '30-04-25', '1.44']

TOP: 102.9
['Andaman', 'And', 'Nicobar', 'Islands', 'North', 'And', 'Middle', 'Andaman', 'Diglipur', 'Nabagram', '13.15474', '92.94847', '30-04-25', '0.55']

TOP: 113.3
['Andaman', 'And', 'Nicobar', 'Islands', 'North', 'And', 'Middle', 'Andaman', 'Diglipur', 'Rest', 'Camp', '12.8328', '92.85923', '30-04-25', '0.49']

In [20]:
def detect_header(rows):

    header_aliases = {
        "State": {
            "STATE",
            "STATE_UT",
            "STATE/UT"
        },

        "District": {
            "DISTRICT"
        },

        "Block": {
            "BLOCK"
        },

        "Village": {
            "VILLAGE"
        },

        "Latitude": {
            "LATITUDE",
            "LATITUTE"
        },

        "Longitude": {
            "LONGITUDE"
        },

        "Date": {
            "DATE"
        },

        "WL_m_bgl": {
            "WL",
            "WL(MBGL)"
        }
    }

    for top, row_words in rows.items():

        row_words = sorted(
            row_words,
            key=lambda x: x["x0"]
        )

        detected = {}

        for word in row_words:

            text = (
                word["text"]
                .upper()
                .strip()
            )

            # Remove spaces
            text = text.replace(
                " ",
                ""
            )

            for column, aliases in header_aliases.items():

                normalized_aliases = {
                    alias.replace(" ", "")
                    for alias in aliases
                }

                if text in normalized_aliases:

                    detected[column] = (
                        word["x0"]
                    )

                    break

        # Need the main structural columns
        required = {
            "State",
            "District",
            "Block",
            "Village",
            "Latitude",
            "Longitude",
            "Date"
        }

        if required.issubset(
            detected.keys()
        ):

            # WL may be embedded in WL(mbgl)
            # or detected separately.
            if "WL_m_bgl" not in detected:

                # Look for WL(mbgl)
                for word in row_words:

                    text = (
                        word["text"]
                        .upper()
                        .replace(" ", "")
                    )

                    if text.startswith("WL"):

                        detected[
                            "WL_m_bgl"
                        ] = word["x0"]

                        break

            return top, detected

    return None, None

In [22]:
import pdfplumber

PDF_PATH = "../raw/Pre-monsoon_WL_1994-2025.pdf"

with pdfplumber.open(PDF_PATH) as pdf:

    for page_number in [1, 2, 400, 401, 402, 500]:

        page = pdf.pages[
            page_number - 1
        ]

        words = page.extract_words()

        rows = {}

        for word in words:

            top = round(
                word["top"],
                1
            )

            rows.setdefault(
                top,
                []
            ).append(word)

        header_top, header_positions = (
            detect_header(rows)
        )

        print(
            f"\nPage {page_number}"
        )

        print(
            "Header top:",
            header_top
        )

        print(
            "Header positions:",
            header_positions
        )

Page 1
Header top: 30.7
Header positions: {'State': 20.159999250000002, 'District': 183.95999925, 'Block': 332.879997, 'Village': 505.43998725, 'Latitude': 650.2799835000001, 'Longitude': 692.16000375, 'Date': 740.8800202499999, 'WL_m_bgl': 781.199982}

Page 2
Header top: 30.7
Header positions: {'State': 20.159999250000002, 'District': 183.95999925, 'Block': 332.879997, 'Village': 505.43998725, 'Latitude': 650.2799835000001, 'Longitude': 692.16000375, 'Date': 740.8800202499999, 'WL_m_bgl': 781.199982}

Page 400
Header top: 36.2
Header positions: {'State': 23.40000075, 'District': 183.49567159043926, 'Block': 323.35171744044567, 'Village': 433.1683113175974, 'Latitude': 572.1775247461256, 'Longitude': 630.6048373547385, 'Date': 706.9523698061089}

Page 401
Header top: 36.2
Header positions: {'State': 23.40000075, 'District': 183.49567159043926, 'Block': 323.35171744044567, 'Village': 433.1683113175974, 'Latitude': 572.1775247461256, 'Longitude': 630.6048373547385, 'Date': 706.9523698061089}

Page 402
Header top: 36.2
Header positions: {'State': 23.40000075, 'District': 183.49567159043926, 'Block': 323.35171744044567, 'Village': 433.1683113175974, 'Latitude': 572.1775247461256, 'Longitude': 630.6048373547385, 'Date': 706.9523698061089}

Page 500
Header top: 36.2
Header positions: {'State': 23.40000075, 'District': 183.49567159043926, 'Block': 323.35171744044567, 'Village': 433.1683113175974, 'Latitude': 572.1775247461256, 'Longitude': 630.6048373547385, 'Date': 706.9523698061089}

In [23]:
def extract_page(page):

    words = page.extract_words()

    if not words:
        return pd.DataFrame()

    # -----------------------------------------------------
    # Group words by row
    # -----------------------------------------------------

    rows = {}

    for word in words:

        top = round(
            word["top"],
            1
        )

        rows.setdefault(
            top,
            []
        ).append(word)

    # -----------------------------------------------------
    # Detect header
    # -----------------------------------------------------

    header_top, header_positions = detect_header(
        rows
    )

    if header_positions is None:
        return pd.DataFrame()

    # -----------------------------------------------------
    # IMPORTANT:
    # If WL wasn't detected, create it as the column
    # immediately after Date.
    # -----------------------------------------------------

    if "WL_m_bgl" not in header_positions:

        date_position = header_positions["Date"]

        header_positions["WL_m_bgl"] = (
            date_position + 1
        )

    # -----------------------------------------------------
    # Sort columns by position
    # -----------------------------------------------------

    ordered_columns = sorted(
        header_positions.items(),
        key=lambda x: x[1]
    )

    # -----------------------------------------------------
    # Create dynamic boundaries
    # -----------------------------------------------------

    boundaries = {}

    for i, (column, position) in enumerate(
        ordered_columns
    ):

        if i == 0:

            left = 0

        else:

            previous_position = (
                ordered_columns[i - 1][1]
            )

            left = (
                previous_position +
                position
            ) / 2

        if i == len(ordered_columns) - 1:

            right = page.width

        else:

            next_position = (
                ordered_columns[i + 1][1]
            )

            right = (
                position +
                next_position
            ) / 2

        boundaries[column] = (
            left,
            right
        )

    # -----------------------------------------------------
    # Extract data rows
    # -----------------------------------------------------

    extracted_rows = []

    for top, row_words in rows.items():

        # Ignore title + header
        if top <= header_top:
            continue

        row_words = sorted(
            row_words,
            key=lambda x: x["x0"]
        )

        row = {
            column: []
            for column in header_positions
        }

        # ---------------------------------------------
        # Assign each word to dynamic column
        # ---------------------------------------------

        for word in row_words:

            x = word["x0"]

            for column, (
                left,
                right
            ) in boundaries.items():

                if left <= x < right:

                    row[column].append(
                        word["text"]
                    )

                    break

        # ---------------------------------------------
        # Join words
        # ---------------------------------------------

        row = {
            column: " ".join(values).strip()
            for column, values in row.items()
        }

        # ---------------------------------------------
        # Validate using data patterns
        # ---------------------------------------------

        latitude = row.get(
            "Latitude",
            ""
        )

        longitude = row.get(
            "Longitude",
            ""
        )

        date = row.get(
            "Date",
            ""
        )

        wl = row.get(
            "WL_m_bgl",
            ""
        )

        try:

            float(latitude)
            float(longitude)
            float(wl)

            valid_coordinates = True

        except:

            valid_coordinates = False

        valid_date = bool(
            re.match(
                r"^\d{2}-\d{2}-\d{2,4}$",
                date
            )
        )

        if (
            valid_coordinates
            and valid_date
        ):

            extracted_rows.append(
                row
            )

    return pd.DataFrame(
        extracted_rows
    )

In [24]:
import pdfplumber

PDF_PATH = "../raw/Pre-monsoon_WL_1994-2025.pdf"

with pdfplumber.open(PDF_PATH) as pdf:

    for page_number in [
        1,
        2,
        400,
        401,
        402,
        500
    ]:

        df = extract_page(
            pdf.pages[page_number - 1]
        )

        print("\n" + "=" * 70)

        print(
            f"PAGE {page_number}"
        )

        print("=" * 70)

        print(
            "Shape:",
            df.shape
        )

        print(
            "Columns:",
            df.columns.tolist()
        )

        print(
            df.head(2).to_string(
                index=False
            )
        )

======================================================================
PAGE 1
======================================================================
Shape: (51, 8)
Columns: ['State', 'District', 'Block', 'Village', 'Latitude', 'Longitude', 'Date', 'WL_m_bgl']
                      State                 District    Block     Village Latitude Longitude     Date WL_m_bgl
Andaman And Nicobar Islands North And Middle Andaman Diglipur    Durgapur 13.27653  93.02364 30-04-25     0.46
Andaman And Nicobar Islands North And Middle Andaman Diglipur Keralapuram  13.2588  93.01351 30-04-25     1.31

======================================================================
PAGE 2
======================================================================
Shape: (49, 8)
Columns: ['State', 'District', 'Block', 'Village', 'Latitude', 'Longitude', 'Date', 'WL_m_bgl']
                      State       District      Block    Village Latitude Longitude     Date WL_m_bgl
Andaman And Nicobar Islands South Andamans Ferrargunj    Manjeri 11.53755  92.64795 30-04-25     0.98
Andaman And Nicobar Islands South Andamans Ferrargunj Mannarghat 11.76734  92.70597 30-04-25     1.93

======================================================================
PAGE 400
======================================================================
Shape: (0, 0)
Columns: []
Empty DataFrame
Columns: []
Index: []

======================================================================
PAGE 401
======================================================================
Shape: (0, 0)
Columns: []
Empty DataFrame
Columns: []
Index: []

======================================================================
PAGE 402
======================================================================
Shape: (0, 0)
Columns: []
Empty DataFrame
Columns: []
Index: []

======================================================================
PAGE 500
======================================================================
Shape: (0, 0)
Columns: []
Empty DataFrame
Columns: []
Index: []

In [25]:
def extract_page(page):

    words = page.extract_words()

    if not words:
        return pd.DataFrame()

    # =====================================================
    # Group words by row
    # =====================================================

    rows = {}

    for word in words:

        top = round(
            word["top"],
            1
        )

        rows.setdefault(
            top,
            []
        ).append(word)

    # =====================================================
    # Detect header
    # =====================================================

    header_top, header_positions = detect_header(
        rows
    )

    if header_positions is None:
        return pd.DataFrame()

    # =====================================================
    # We only use the actual detected header columns.
    # WL is handled separately from the data row.
    # =====================================================

    base_columns = [
        "State",
        "District",
        "Block",
        "Village",
        "Latitude",
        "Longitude",
        "Date"
    ]

    # Make sure all seven exist
    if not all(
        column in header_positions
        for column in base_columns
    ):
        return pd.DataFrame()

    # =====================================================
    # Sort the 7 known columns
    # =====================================================

    ordered_columns = sorted(
        base_columns,
        key=lambda column:
            header_positions[column]
    )

    # =====================================================
    # Calculate boundaries for the 7 known columns
    # =====================================================

    boundaries = {}

    for i, column in enumerate(
        ordered_columns
    ):

        position = header_positions[column]

        if i == 0:

            left = 0

        else:

            previous_position = (
                header_positions[
                    ordered_columns[i - 1]
                ]
            )

            left = (
                previous_position +
                position
            ) / 2

        if i == len(ordered_columns) - 1:

            # Date extends until the end of
            # the data row. WL will be extracted
            # separately.
            right = page.width

        else:

            next_position = (
                header_positions[
                    ordered_columns[i + 1]
                ]
            )

            right = (
                position +
                next_position
            ) / 2

        boundaries[column] = (
            left,
            right
        )

    # =====================================================
    # Regex patterns
    # =====================================================

    number_pattern = re.compile(
        r"^-?\d+(?:\.\d+)?$"
    )

    date_pattern = re.compile(
        r"^\d{2}-\d{2}-\d{2,4}$"
    )

    # =====================================================
    # Extract rows
    # =====================================================

    extracted_rows = []

    for top, row_words in rows.items():

        if top <= header_top:
            continue

        row_words = sorted(
            row_words,
            key=lambda x: x["x0"]
        )

        # -----------------------------------------------
        # First collect words by the 7 header regions
        # -----------------------------------------------

        row = {
            column: []
            for column in ordered_columns
        }

        for word in row_words:

            x = word["x0"]

            for column in ordered_columns:

                left, right = boundaries[column]

                if left <= x < right:

                    row[column].append(
                        word["text"]
                    )

                    break

        # -----------------------------------------------
        # Join normal columns
        # -----------------------------------------------

        row = {
            column: " ".join(
                values
            ).strip()

            for column, values
            in row.items()
        }

        # -----------------------------------------------
        # The Date region may contain BOTH Date and WL.
        #
        # Example:
        #
        # Date region:
        # 10-05-24 11.4
        #
        # Extract them using patterns.
        # -----------------------------------------------

        date_region = row["Date"]

        tokens = date_region.split()

        date_value = None
        wl_value = None

        for token in tokens:

            if date_pattern.match(token):

                date_value = token

            elif number_pattern.match(token):

                wl_value = token

        # -----------------------------------------------
        # Validate coordinates
        # -----------------------------------------------

        try:

            latitude = float(
                row["Latitude"]
            )

            longitude = float(
                row["Longitude"]
            )

            wl = float(
                wl_value
            )

            valid_numeric = True

        except:

            valid_numeric = False

        # -----------------------------------------------
        # Validate date
        # -----------------------------------------------

        valid_date = (
            date_value is not None
        )

        # -----------------------------------------------
        # Save valid observation
        # -----------------------------------------------

        if (
            valid_numeric
            and valid_date
        ):

            extracted_rows.append({

                "State":
                    row["State"],

                "District":
                    row["District"],

                "Block":
                    row["Block"],

                "Village":
                    row["Village"],

                "Latitude":
                    row["Latitude"],

                "Longitude":
                    row["Longitude"],

                "Date":
                    date_value,

                "WL_m_bgl":
                    wl_value
            })

    return pd.DataFrame(
        extracted_rows
    )

In [26]:
import pdfplumber

PDF_PATH = "../raw/Pre-monsoon_WL_1994-2025.pdf"

with pdfplumber.open(PDF_PATH) as pdf:

    for page_number in [
        1,
        2,
        400,
        401,
        402,
        500
    ]:

        df = extract_page(
            pdf.pages[
                page_number - 1
            ]
        )

        print(
            "\n" + "=" * 70
        )

        print(
            f"PAGE {page_number}"
        )

        print(
            "=" * 70
        )

        print(
            "Shape:",
            df.shape
        )

        if not df.empty:

            print(
                df.head(2).to_string(
                    index=False
                )
            )

======================================================================
PAGE 1
======================================================================
Shape: (51, 8)
                      State                 District    Block     Village Latitude Longitude     Date WL_m_bgl
Andaman And Nicobar Islands North And Middle Andaman Diglipur    Durgapur 13.27653  93.02364 30-04-25     0.46
Andaman And Nicobar Islands North And Middle Andaman Diglipur Keralapuram  13.2588  93.01351 30-04-25     1.31

======================================================================
PAGE 2
======================================================================
Shape: (49, 8)
                      State       District      Block    Village Latitude Longitude     Date WL_m_bgl
Andaman And Nicobar Islands South Andamans Ferrargunj    Manjeri 11.53755  92.64795 30-04-25     0.98
Andaman And Nicobar Islands South Andamans Ferrargunj Mannarghat 11.76734  92.70597 30-04-25     1.93

======================================================================
PAGE 400
======================================================================
Shape: (0, 0)

======================================================================
PAGE 401
======================================================================
Shape: (0, 0)

======================================================================
PAGE 402
======================================================================
Shape: (0, 0)

======================================================================
PAGE 500
======================================================================
Shape: (0, 0)

In [27]:
import pdfplumber
import pandas as pd
import re

PDF_PATH = "../raw/Pre-monsoon_WL_1994-2025.pdf"


DATE_RE = re.compile(
    r"^\d{2}-\d{2}-\d{2,4}$"
)

NUMBER_RE = re.compile(
    r"^-?\d+(?:\.\d+)?$"
)


def is_number(value):
    return bool(NUMBER_RE.match(value))


def is_date(value):
    return bool(DATE_RE.match(value))


def extract_page(page):

    words = page.extract_words()

    if not words:
        return pd.DataFrame()

    # --------------------------------------------------
    # Group words into visual rows
    # --------------------------------------------------

    rows = {}

    for word in words:

        top = round(
            word["top"],
            1
        )

        rows.setdefault(
            top,
            []
        ).append(word)

    # --------------------------------------------------
    # Find the header row
    # --------------------------------------------------

    header_top = None

    for top, row_words in rows.items():

        texts = [
            w["text"].upper()
            for w in row_words
        ]

        joined = " ".join(texts)

        if (
            "STATE" in joined
            and "DISTRICT" in joined
            and "BLOCK" in joined
            and "VILLAGE" in joined
            and "LATITUDE" in joined
        ):
            header_top = top
            break

    if header_top is None:

        return pd.DataFrame()

    extracted = []

    # --------------------------------------------------
    # Process data rows
    # --------------------------------------------------

    for top, row_words in rows.items():

        if top <= header_top:
            continue

        row_words = sorted(
            row_words,
            key=lambda w: w["x0"]
        )

        tokens = [
            w["text"]
            for w in row_words
        ]

        # ----------------------------------------------
        # Find DATE
        # ----------------------------------------------

        date_index = None

        for i, token in enumerate(tokens):

            if is_date(token):

                date_index = i
                break

        if date_index is None:
            continue

        # ----------------------------------------------
        # Need something after DATE for WL
        # ----------------------------------------------

        if date_index + 1 >= len(tokens):

            continue

        wl_token = tokens[
            date_index + 1
        ]

        if not is_number(wl_token):

            continue

        # ----------------------------------------------
        # Latitude and longitude should immediately
        # precede the date.
        # ----------------------------------------------

        if date_index < 2:
            continue

        latitude_token = tokens[
            date_index - 2
        ]

        longitude_token = tokens[
            date_index - 1
        ]

        if not is_number(
            latitude_token
        ):
            continue

        if not is_number(
            longitude_token
        ):
            continue

        # ----------------------------------------------
        # Everything before latitude belongs to:
        #
        # State
        # District
        # Block
        # Village
        #
        # We use the detected column x positions to
        # assign those text tokens.
        # ----------------------------------------------

        latitude_word = row_words[
            date_index - 2
        ]

        longitude_word = row_words[
            date_index - 1
        ]

        date_word = row_words[
            date_index
        ]

        wl_word = row_words[
            date_index + 1
        ]

        # ------------------------------------------------
        # Use actual positions of the data anchors to
        # divide the text before latitude.
        #
        # No hard-coded page coordinates.
        # ------------------------------------------------

        anchor_positions = [
            latitude_word["x0"],
            longitude_word["x0"],
            date_word["x0"],
            wl_word["x0"]
        ]

        # Find the header positions on this page
        # for the first four textual columns.
        #
        # We only use their relative order.
        # ------------------------------------------------

        state_words = []
        district_words = []
        block_words = []
        village_words = []

        # Get header words
        header_words = sorted(
            rows[header_top],
            key=lambda w: w["x0"]
        )

        header_map = {}

        for w in header_words:

            text = (
                w["text"]
                .upper()
                .strip()
            )

            if text in (
                "STATE",
                "STATE_UT"
            ):
                header_map["State"] = w["x0"]

            elif text == "DISTRICT":
                header_map["District"] = w["x0"]

            elif text == "BLOCK":
                header_map["Block"] = w["x0"]

            elif text == "VILLAGE":
                header_map["Village"] = w["x0"]

        required = [
            "State",
            "District",
            "Block",
            "Village"
        ]

        if not all(
            x in header_map
            for x in required
        ):
            continue

        # ------------------------------------------------
        # Calculate boundaries between textual columns
        # using THIS PAGE'S header positions.
        # ------------------------------------------------

        text_columns = [
            (
                "State",
                header_map["State"]
            ),
            (
                "District",
                header_map["District"]
            ),
            (
                "Block",
                header_map["Block"]
            ),
            (
                "Village",
                header_map["Village"]
            )
        ]

        text_columns.sort(
            key=lambda x: x[1]
        )

        boundaries = {}

        for i, (
            column,
            position
        ) in enumerate(text_columns):

            if i == 0:

                left = 0

            else:

                previous = (
                    text_columns[i - 1][1]
                )

                left = (
                    previous + position
                ) / 2

            if i == len(text_columns) - 1:

                right = latitude_word["x0"]

            else:

                next_position = (
                    text_columns[i + 1][1]
                )

                right = (
                    position +
                    next_position
                ) / 2

            boundaries[column] = (
                left,
                right
            )

        # ------------------------------------------------
        # Assign text words
        # ------------------------------------------------

        text_values = {
            "State": [],
            "District": [],
            "Block": [],
            "Village": []
        }

        for word in row_words:

            x = word["x0"]

            # Don't process numeric anchor fields
            if x >= latitude_word["x0"]:
                continue

            for column, (
                left,
                right
            ) in boundaries.items():

                if left <= x < right:

                    text_values[
                        column
                    ].append(
                        word["text"]
                    )

                    break

        # ------------------------------------------------
        # Create final row
        # ------------------------------------------------

        extracted.append({

            "State":
                " ".join(
                    text_values["State"]
                ).strip(),

            "District":
                " ".join(
                    text_values["District"]
                ).strip(),

            "Block":
                " ".join(
                    text_values["Block"]
                ).strip(),

            "Village":
                " ".join(
                    text_values["Village"]
                ).strip(),

            "Latitude":
                latitude_token,

            "Longitude":
                longitude_token,

            "Date":
                tokens[date_index],

            "WL_m_bgl":
                wl_token
        })

    return pd.DataFrame(
        extracted
    )

In [28]:
with pdfplumber.open(PDF_PATH) as pdf:

    for page_number in [
        1,
        2,
        400,
        401,
        402,
        500
    ]:

        df = extract_page(
            pdf.pages[page_number - 1]
        )

        print(
            f"\nPAGE {page_number}"
        )

        print(
            "Shape:",
            df.shape
        )

        if not df.empty:

            print(
                df.head(3).to_string(
                    index=False
                )
            )

PAGE 1
Shape: (0, 0)

PAGE 2
Shape: (0, 0)

PAGE 400
Shape: (0, 0)

PAGE 401
Shape: (0, 0)

PAGE 402
Shape: (0, 0)

PAGE 500
Shape: (0, 0)

In [29]:
import pandas as pd

In [30]:
ground_water_df = pd.read_csv("../raw/groundwater/Pre-monsoon_WL_1994-2025.csv")

In [32]:
ground_water_df.tail(3)

,State,District,Block,Village,Latitude,Longitude,Date,WL_mbgl
394686,West Bengal,Purba Bardhaman,Manteswar,Bamunpara,23.47000,88.19000,1994-04-01,4.91
394687,West Bengal,Purba Bardhaman,Memari-1,Memari,23.18056,88.09222,1994-04-01,3.85
394688,West Bengal,Purba Bardhaman,Memari-1,Pallaroad,23.17389,88.00750,1994-04-01,4.32

In [33]:
import pandas as pd

GROUNDWATER_PATH = "../raw/groundwater/Pre-monsoon_WL_1994-2025.csv"

gw = pd.read_csv(
    GROUNDWATER_PATH
)

print("Shape:", gw.shape)

print("\nColumns:")
print(gw.columns.tolist())

print("\nFirst 5 rows:")
print(gw.head())

print("\nData types:")
print(gw.dtypes)

print("\nMissing values:")
print(gw.isna().sum())

print("\nDuplicate rows:")
print(gw.duplicated().sum())

Shape: (394689, 8)

Columns:
['State', 'District', 'Block', 'Village', 'Latitude', 'Longitude', 'Date', 'WL_mbgl']

First 5 rows:
                         State                  District     Block  \
0  Andaman And Nicobar Islands  North And Middle Andaman  Diglipur
1  Andaman And Nicobar Islands  North And Middle Andaman  Diglipur
2  Andaman And Nicobar Islands  North And Middle Andaman  Diglipur
3  Andaman And Nicobar Islands  North And Middle Andaman  Diglipur
4  Andaman And Nicobar Islands  North And Middle Andaman  Diglipur

                    Village  Latitude  Longitude        Date  WL_mbgl
0                  Durgapur  13.27653   93.02364  2025-04-30     0.46
1               Keralapuram  13.25880   93.01351  2025-04-30     1.31
2  Kishorinagar (Parangara)  13.16506   92.88164  2025-04-30     2.21
3                  Laxmipur  13.28734   92.96404  2025-04-30     1.46
4                 Milangram  13.31475   92.94309  2025-04-30     1.01

Data types:
State            str
District         str
Block            str
Village          str
Latitude     float64
Longitude    float64
Date             str
WL_mbgl      float64
dtype: object

Missing values:
State        0
District     0
Block        0
Village      0
Latitude     0
Longitude    0
Date         0
WL_mbgl      1
dtype: int64

Duplicate rows:
249

In [34]:
# =========================================================
# STEP 2 — DUPLICATE + MISSING VALUE INVESTIGATION
# =========================================================

# 1. Show the rows with missing groundwater level
print("Missing WL rows:")
print(
    gw[gw["WL_mbgl"].isna()].to_string(index=False)
)


# 2. Count exact duplicate rows
duplicate_rows = gw[
    gw.duplicated(
        keep=False
    )
].sort_values(
    [
        "State",
        "District",
        "Block",
        "Village",
        "Date"
    ]
)

print("\nTotal rows involved in exact duplicates:")
print(len(duplicate_rows))


# 3. Show some duplicate examples
print("\nFirst 20 duplicate rows:")
print(
    duplicate_rows.head(20).to_string(
        index=False
    )
)


# 4. Check whether duplicate rows are truly identical
print("\nExact duplicate count:")
print(
    gw.duplicated().sum()
)


# 5. Check whether duplicates occur within the
# same location/date but have different WL values

location_date_cols = [
    "State",
    "District",
    "Block",
    "Village",
    "Latitude",
    "Longitude",
    "Date"
]

location_date_duplicates = (
    gw[
        gw.duplicated(
            subset=location_date_cols,
            keep=False
        )
    ]
    .sort_values(location_date_cols)
)

print(
    "\nRows sharing the same "
    "location + date:"
)

print(
    len(location_date_duplicates)
)

print(
    location_date_duplicates.head(30).to_string(
        index=False
    )
)

Missing WL rows:
      State District    Block Village  Latitude  Longitude       Date  WL_mbgl
Uttarakhand Dehradun Sahaspur  Jhajra  30.43861   77.74778 2019-05-01      NaN

Total rows involved in exact duplicates:
498

First 20 duplicate rows:
         State              District     Block         Village  Latitude  Longitude       Date  WL_mbgl
Andhra Pradesh Alluri Sitharama Raju Nellipaka    Lakshmipuram  17.71967   81.04836 2011-05-01     8.74
Andhra Pradesh Alluri Sitharama Raju Nellipaka    Lakshmipuram  17.71967   81.04836 2011-05-01     8.74
Andhra Pradesh Alluri Sitharama Raju Nellipaka    Lakshmipuram  17.71967   81.04836 2012-05-01     9.60
Andhra Pradesh Alluri Sitharama Raju Nellipaka    Lakshmipuram  17.71967   81.04836 2012-05-01     9.60
Andhra Pradesh Alluri Sitharama Raju Nellipaka    Lakshmipuram  17.71967   81.04836 2016-05-01     9.09
Andhra Pradesh Alluri Sitharama Raju Nellipaka    Lakshmipuram  17.71967   81.04836 2016-05-01     9.09
Andhra Pradesh Alluri Sitharama Raju Nellipaka    Lakshmipuram  17.71967   81.04836 2022-05-01     9.50
Andhra Pradesh Alluri Sitharama Raju Nellipaka    Lakshmipuram  17.71967   81.04836 2022-05-01     9.50
Andhra Pradesh Alluri Sitharama Raju Nellipaka    Lakshmipuram  17.71967   81.04836 2023-05-01     8.50
Andhra Pradesh Alluri Sitharama Raju Nellipaka    Lakshmipuram  17.71967   81.04836 2023-05-01     8.50
Andhra Pradesh        Sri Sathya Sai Mudigubba Kodavandlapalli  14.46770   77.96290 2023-05-01     6.70
Andhra Pradesh        Sri Sathya Sai Mudigubba Kodavandlapalli  14.46770   77.96290 2023-05-01     6.70
Andhra Pradesh        Sri Sathya Sai Mudigubba Kodavandlapalli  14.46770   77.96290 2024-05-10     7.30
Andhra Pradesh        Sri Sathya Sai Mudigubba Kodavandlapalli  14.46770   77.96290 2024-05-10     7.30
         Bihar                Araria   Jokihat         Jokihat  26.14583   87.65417 2000-05-01     3.85
         Bihar                Araria   Jokihat         Jokihat  26.14583   87.65417 2000-05-01     3.85
         Bihar                Araria   Jokihat         Jokihat  26.14583   87.65417 2018-05-30     2.10
         Bihar                Araria   Jokihat         Jokihat  26.14583   87.65417 2018-05-30     2.10
         Bihar                Purnia     Baisi           Baisi  25.88333   87.74167 2000-05-01     3.39
         Bihar                Purnia     Baisi           Baisi  25.88333   87.74167 2000-05-01     3.39

Exact duplicate count:
249

Rows sharing the same location + date:
4114
         State              District     Block        Village  Latitude  Longitude       Date  WL_mbgl
Andhra Pradesh Alluri Sitharama Raju Nellipaka   Lakshmipuram  17.71967   81.04836 2011-05-01     8.74
Andhra Pradesh Alluri Sitharama Raju Nellipaka   Lakshmipuram  17.71967   81.04836 2011-05-01     8.74
Andhra Pradesh Alluri Sitharama Raju Nellipaka   Lakshmipuram  17.71967   81.04836 2012-05-01     9.60
Andhra Pradesh Alluri Sitharama Raju Nellipaka   Lakshmipuram  17.71967   81.04836 2012-05-01     9.60
Andhra Pradesh Alluri Sitharama Raju Nellipaka   Lakshmipuram  17.71967   81.04836 2014-05-01     8.82
Andhra Pradesh Alluri Sitharama Raju Nellipaka   Lakshmipuram  17.71967   81.04836 2014-05-01     8.98
Andhra Pradesh Alluri Sitharama Raju Nellipaka   Lakshmipuram  17.71967   81.04836 2015-05-01     9.40
Andhra Pradesh Alluri Sitharama Raju Nellipaka   Lakshmipuram  17.71967   81.04836 2015-05-01     9.79
Andhra Pradesh Alluri Sitharama Raju Nellipaka   Lakshmipuram  17.71967   81.04836 2016-05-01     9.09
Andhra Pradesh Alluri Sitharama Raju Nellipaka   Lakshmipuram  17.71967   81.04836 2016-05-01     9.09
Andhra Pradesh Alluri Sitharama Raju Nellipaka   Lakshmipuram  17.71967   81.04836 2017-05-01     9.43
Andhra Pradesh Alluri Sitharama Raju Nellipaka   Lakshmipuram  17.71967   81.04836 2017-05-01     9.60
Andhra Pradesh Alluri Sitharama Raju Nellipaka   Lakshmipuram  17.71967   81.04836 2018-05-01    10.64
Andhra Pradesh Alluri Sitharama Raju Nellipaka   Lakshmipuram  17.71967   81.04836 2018-05-01    10.85
Andhra Pradesh Alluri Sitharama Raju Nellipaka   Lakshmipuram  17.71967   81.04836 2019-05-01     9.40
Andhra Pradesh Alluri Sitharama Raju Nellipaka   Lakshmipuram  17.71967   81.04836 2019-05-01    10.20
Andhra Pradesh Alluri Sitharama Raju Nellipaka   Lakshmipuram  17.71967   81.04836 2022-05-01     9.50
Andhra Pradesh Alluri Sitharama Raju Nellipaka   Lakshmipuram  17.71967   81.04836 2022-05-01     9.50
Andhra Pradesh Alluri Sitharama Raju Nellipaka   Lakshmipuram  17.71967   81.04836 2023-05-01     8.50
Andhra Pradesh Alluri Sitharama Raju Nellipaka   Lakshmipuram  17.71967   81.04836 2023-05-01     8.50
Andhra Pradesh         Ananthapuramu Beluguppa     Ramasagram  14.72320   77.25600 2024-05-10    15.60
Andhra Pradesh         Ananthapuramu Beluguppa     Ramasagram  14.72320   77.25600 2024-05-10    16.90
Andhra Pradesh         Ananthapuramu Beluguppa     Ramasagram  14.72320   77.25600 2025-05-25     7.64
Andhra Pradesh         Ananthapuramu Beluguppa     Ramasagram  14.72320   77.25600 2025-05-25     8.15
Andhra Pradesh         Ananthapuramu   Narpala    Nayanapalle  14.80200   77.81370 2024-05-10    18.30
Andhra Pradesh         Ananthapuramu   Narpala    Nayanapalle  14.80200   77.81370 2024-05-10     6.90
Andhra Pradesh         Ananthapuramu   Narpala    Nayanapalle  14.80200   77.81370 2025-05-25    25.61
Andhra Pradesh         Ananthapuramu   Narpala    Nayanapalle  14.80200   77.81370 2025-05-25    26.16
Andhra Pradesh         Ananthapuramu    Pamidi Sorakayalapeta  14.94410   77.52510 2023-05-01     2.20
Andhra Pradesh         Ananthapuramu    Pamidi Sorakayalapeta  14.94410   77.52510 2023-05-01     2.10

In [35]:
# =========================================================
# STEP 3 — BASIC CLEANING
# =========================================================

gw_clean = gw.copy()

print("Original rows:", len(gw_clean))


# ---------------------------------------------------------
# 1. Parse date
# ---------------------------------------------------------

gw_clean["Date"] = pd.to_datetime(
    gw_clean["Date"],
    errors="coerce"
)


# ---------------------------------------------------------
# 2. Ensure numeric columns are numeric
# ---------------------------------------------------------

gw_clean["Latitude"] = pd.to_numeric(
    gw_clean["Latitude"],
    errors="coerce"
)

gw_clean["Longitude"] = pd.to_numeric(
    gw_clean["Longitude"],
    errors="coerce"
)

gw_clean["WL_mbgl"] = pd.to_numeric(
    gw_clean["WL_mbgl"],
    errors="coerce"
)


# ---------------------------------------------------------
# 3. Check parsing failures
# ---------------------------------------------------------

print("\nDate parsing failures:")
print(
    gw_clean["Date"].isna().sum()
)

print("\nLatitude parsing failures:")
print(
    gw_clean["Latitude"].isna().sum()
)

print("\nLongitude parsing failures:")
print(
    gw_clean["Longitude"].isna().sum()
)

print("\nWL missing:")
print(
    gw_clean["WL_mbgl"].isna().sum()
)


# ---------------------------------------------------------
# 4. Remove ONLY exact duplicates
# ---------------------------------------------------------

before = len(gw_clean)

gw_clean = gw_clean.drop_duplicates(
    keep="first"
).reset_index(
    drop=True
)

after = len(gw_clean)

print("\nExact duplicates removed:")
print(before - after)

print("Rows after deduplication:")
print(after)


# ---------------------------------------------------------
# 5. Create temporal features
# ---------------------------------------------------------

gw_clean["Year"] = (
    gw_clean["Date"].dt.year
)

gw_clean["Month"] = (
    gw_clean["Date"].dt.month
)


# ---------------------------------------------------------
# 6. Season
# ---------------------------------------------------------

gw_clean["Season"] = "Pre-Monsoon"

print("\nFinal shape:")
print(
    gw_clean.shape
)

print("\nColumns:")
print(
    gw_clean.columns.tolist()
)

print("\nDate range:")
print(
    gw_clean["Date"].min(),
    "→",
    gw_clean["Date"].max()
)

Original rows: 394689

Date parsing failures:
0

Latitude parsing failures:
0

Longitude parsing failures:
0

WL missing:
1

Exact duplicates removed:
249
Rows after deduplication:
394440

Final shape:
(394440, 11)

Columns:
['State', 'District', 'Block', 'Village', 'Latitude', 'Longitude', 'Date', 'WL_mbgl', 'Year', 'Month', 'Season']

Date range:
1994-04-01 00:00:00 → 2025-05-30 00:00:00

In [36]:
# =========================================================
# CHECK STATE / DISTRICT NAME CONSISTENCY
# =========================================================

print("\nNumber of states:")
print(
    gw_clean["State"].nunique()
)

print("\nStates:")
print(
    sorted(
        gw_clean["State"].dropna().unique()
    )
)


print("\nNumber of districts:")
print(
    gw_clean["District"].nunique()
)


print("\nDistricts by state:")
district_counts = (
    gw_clean
    .groupby("State")["District"]
    .nunique()
    .sort_values(
        ascending=False
    )
)

print(
    district_counts
)

Number of states:
35

States:
['Andaman And Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra And Nagar Haveli & Daman And Diu', 'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu And Kashmir', 'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Tamil Nadu', 'Telangana', 'The Dadra And Nagar Haveli And Daman And Diu', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']

Number of districts:
715

Districts by state:
State
Uttar Pradesh                                   75
Madhya Pradesh                                  56
Rajasthan                                       50
Tamil Nadu                                      38
Bihar                                           38
Maharashtra                                     36
Chhattisgarh                                    33
Gujarat                                         33
Telangana                                       33
Assam                                           33
Karnataka                                       31
Odisha                                          30
Andhra Pradesh                                  26
Jharkhand                                       24
Punjab                                          23
West Bengal                                     22
Haryana                                         22
Kerala                                          14
Uttarakhand                                     13
Jammu And Kashmir                               13
Jammu and Kashmir                               13
Delhi                                           12
Meghalaya                                       11
Himachal Pradesh                                 9
Arunachal Pradesh                                9
Nagaland                                         8
Tripura                                          8
Mizoram                                          5
The Dadra And Nagar Haveli And Daman And Diu     3
Dadra And Nagar Haveli & Daman And Diu           3
Manipur                                          3
Andaman And Nicobar Islands                      2
Goa                                              2
Puducherry                                       2
Chandigarh                                       1
Name: District, dtype: int64

In [37]:
# =========================================================
# STEP 4 — FIND POSSIBLE STATE NAME VARIANTS
# =========================================================

import re


def normalize_for_comparison(text):

    if pd.isna(text):
        return ""

    text = str(text).strip().lower()

    # Replace &, punctuation with spaces
    text = text.replace("&", " and ")

    text = re.sub(
        r"[^a-z0-9\s]",
        " ",
        text
    )

    # Collapse whitespace
    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()


state_check = (
    gw_clean[
        ["State"]
    ]
    .drop_duplicates()
    .copy()
)

state_check["Comparison_Name"] = (
    state_check["State"]
    .apply(normalize_for_comparison)
)

print(
    state_check
    .sort_values("Comparison_Name")
    .to_string(index=False)
)

                                       State                              Comparison_Name
                 Andaman And Nicobar Islands                  andaman and nicobar islands
                              Andhra Pradesh                               andhra pradesh
                           Arunachal Pradesh                            arunachal pradesh
                                       Assam                                        assam
                                       Bihar                                        bihar
                                  Chandigarh                                   chandigarh
                                Chhattisgarh                                 chhattisgarh
      Dadra And Nagar Haveli & Daman And Diu     dadra and nagar haveli and daman and diu
                                       Delhi                                        delhi
                                         Goa                                          goa
                                     Gujarat                                      gujarat
                                     Haryana                                      haryana
                            Himachal Pradesh                             himachal pradesh
                           Jammu And Kashmir                            jammu and kashmir
                           Jammu and Kashmir                            jammu and kashmir
                                   Jharkhand                                    jharkhand
                                   Karnataka                                    karnataka
                                      Kerala                                       kerala
                              Madhya Pradesh                               madhya pradesh
                                 Maharashtra                                  maharashtra
                                     Manipur                                      manipur
                                   Meghalaya                                    meghalaya
                                     Mizoram                                      mizoram
                                    Nagaland                                     nagaland
                                      Odisha                                       odisha
                                  Puducherry                                   puducherry
                                      Punjab                                       punjab
                                   Rajasthan                                    rajasthan
                                  Tamil Nadu                                   tamil nadu
                                   Telangana                                    telangana
The Dadra And Nagar Haveli And Daman And Diu the dadra and nagar haveli and daman and diu
                                     Tripura                                      tripura
                               Uttar Pradesh                                uttar pradesh
                                 Uttarakhand                                  uttarakhand
                                 West Bengal                                  west bengal

In [38]:
# =========================================================
# FIND POSSIBLE DISTRICT NAME VARIANTS
# =========================================================

district_check = (
    gw_clean[
        ["State", "District"]
    ]
    .drop_duplicates()
    .copy()
)

district_check["Comparison_State"] = (
    district_check["State"]
    .apply(normalize_for_comparison)
)

district_check["Comparison_District"] = (
    district_check["District"]
    .apply(normalize_for_comparison)
)


# Find cases where the same normalized
# state + district has multiple source names.

possible_variants = (
    district_check
    .groupby(
        [
            "Comparison_State",
            "Comparison_District"
        ]
    )
    .filter(
        lambda x: len(x) > 1
    )
    .sort_values(
        [
            "Comparison_State",
            "Comparison_District"
        ]
    )
)


print(
    "Possible district naming variants:"
)

print(
    possible_variants.to_string(
        index=False
    )
)

Possible district naming variants:
            State  District  Comparison_State Comparison_District
Jammu And Kashmir Bandipora jammu and kashmir           bandipora
Jammu and Kashmir Bandipora jammu and kashmir           bandipora
Jammu And Kashmir Baramulla jammu and kashmir           baramulla
Jammu and Kashmir Baramulla jammu and kashmir           baramulla
Jammu And Kashmir Ganderbal jammu and kashmir           ganderbal
Jammu and Kashmir Ganderbal jammu and kashmir           ganderbal
Jammu And Kashmir     Jammu jammu and kashmir               jammu
Jammu and Kashmir     Jammu jammu and kashmir               jammu
Jammu And Kashmir    Kathua jammu and kashmir              kathua
Jammu and Kashmir    Kathua jammu and kashmir              kathua
Jammu And Kashmir   Kupwara jammu and kashmir             kupwara
Jammu and Kashmir   Kupwara jammu and kashmir             kupwara
Jammu And Kashmir    Poonch jammu and kashmir              poonch
Jammu and Kashmir    Poonch jammu and kashmir              poonch
Jammu And Kashmir   Pulwama jammu and kashmir             pulwama
Jammu and Kashmir   Pulwama jammu and kashmir             pulwama
Jammu And Kashmir   Rajouri jammu and kashmir             rajouri
Jammu and Kashmir   Rajouri jammu and kashmir             rajouri
Jammu And Kashmir     Reasi jammu and kashmir               reasi
Jammu and Kashmir     Reasi jammu and kashmir               reasi
Jammu And Kashmir     Samba jammu and kashmir               samba
Jammu and Kashmir     Samba jammu and kashmir               samba
Jammu And Kashmir  Srinagar jammu and kashmir            srinagar
Jammu and Kashmir  Srinagar jammu and kashmir            srinagar
Jammu And Kashmir  Udhampur jammu and kashmir            udhampur
Jammu and Kashmir  Udhampur jammu and kashmir            udhampur
   Madhya Pradesh   MAUGANJ    madhya pradesh             mauganj
   Madhya Pradesh   Mauganj    madhya pradesh             mauganj

In [39]:
# =========================================================
# STEP 5 — STANDARDIZE STATE / DISTRICT TEXT
# =========================================================

def standardize_text(text):

    if pd.isna(text):
        return text

    text = str(text).strip()

    # Normalize ampersand
    text = text.replace("&", "and")

    # Remove repeated whitespace
    text = re.sub(
        r"\s+",
        " ",
        text
    )

    # Consistent capitalization
    text = text.title()

    return text


gw_clean["State_Standard"] = (
    gw_clean["State"]
    .apply(standardize_text)
)

gw_clean["District_Standard"] = (
    gw_clean["District"]
    .apply(standardize_text)
)


print("Standardized states:")
print(
    sorted(
        gw_clean["State_Standard"]
        .dropna()
        .unique()
    )
)

print(
    "\nNumber of standardized states:",
    gw_clean["State_Standard"].nunique()
)

print(
    "\nNumber of standardized districts:",
    gw_clean["District_Standard"].nunique()
)

Standardized states:
['Andaman And Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra And Nagar Haveli And Daman And Diu', 'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu And Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Tamil Nadu', 'Telangana', 'The Dadra And Nagar Haveli And Daman And Diu', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']

Number of standardized states: 34

Number of standardized districts: 714

In [40]:
state_summary = (
    gw_clean
    .groupby(
        "State_Standard"
    )
    .agg(
        Observations=(
            "WL_mbgl",
            "size"
        ),
        Districts=(
            "District_Standard",
            "nunique"
        ),
        Min_Year=(
            "Year",
            "min"
        ),
        Max_Year=(
            "Year",
            "max"
        )
    )
    .sort_values(
        "Observations",
        ascending=False
    )
)

print(
    state_summary.to_string()
)

                                              Observations  Districts  Min_Year  Max_Year
State_Standard
Maharashtra                                          40660         36      1994      2025
Madhya Pradesh                                       34301         55      1994      2025
Odisha                                               32772         30      1994      2025
Rajasthan                                            30135         50      1994      2025
Uttar Pradesh                                        29568         75      1994      2025
Karnataka                                            28602         31      1994      2025
Kerala                                               26135         14      1994      2025
Gujarat                                              23740         33      1994      2025
Andhra Pradesh                                       19612         26      1994      2025
Chhattisgarh                                         18387         33      1994      2025
Haryana                                              15391         22      1994      2025
West Bengal                                          13310         22      1994      2025
Punjab                                               13133         23      1994      2025
Bihar                                                12336         38      1994      2025
Tamil Nadu                                           11791         38      1994      2025
Telangana                                             9236         33      1994      2025
Assam                                                 7128         33      1994      2025
Jharkhand                                             6260         24      1994      2025
Jammu And Kashmir                                     5638         13      1994      2025
Delhi                                                 3555         12      1994      2025
Uttarakhand                                           2820         13      1994      2025
Himachal Pradesh                                      2560          9      1994      2025
Andaman And Nicobar Islands                           1839          2      2000      2025
Goa                                                   1542          2      1994      2025
Tripura                                               1300          8      1994      2025
Meghalaya                                             1021         11      1994      2025
Arunachal Pradesh                                      496          9      1994      2025
The Dadra And Nagar Haveli And Daman And Diu           393          3      1994      2024
Nagaland                                               343          8      1994      2025
Chandigarh                                             236          1      1994      2025
Puducherry                                             135          2      1995      2025
Dadra And Nagar Haveli And Daman And Diu                37          3      2025      2025
Manipur                                                 17          3      1994      2025
Mizoram                                                 11          5      2024      2025

In [41]:
# =========================================================
# STEP 6 — FIX CONFIRMED STATE NAME VARIANT
# =========================================================

gw_clean["State_Standard"] = (
    gw_clean["State_Standard"]
    .replace({
        "The Dadra And Nagar Haveli And Daman And Diu":
            "Dadra And Nagar Haveli And Daman And Diu"
    })
)

print(
    "Standardized states:",
    gw_clean["State_Standard"].nunique()
)

print("\nDadra/Daman observations:")
print(
    gw_clean[
        gw_clean["State_Standard"]
        == "Dadra And Nagar Haveli And Daman And Diu"
    ]
    .groupby("Year")
    .size()
)

Standardized states: 33

Dadra/Daman observations:
Year
1994     4
1995     4
1996     3
1997     4
1998     3
1999     3
2000     3
2001     1
2002     4
2003     3
2004     4
2005     5
2006    10
2007     4
2008    10
2009     8
2010     9
2011    11
2012    10
2013    11
2014    22
2015    22
2016    28
2017    30
2018    27
2019    29
2020    16
2021     6
2022    32
2023    26
2024    41
2025    37
dtype: int64

In [42]:
# =========================================================
# STEP 7 — MONITORING LOCATION ANALYSIS
# =========================================================

location_cols = [
    "State_Standard",
    "District_Standard",
    "Latitude",
    "Longitude"
]

# Unique physical-ish monitoring locations
station_summary = (
    gw_clean
    .groupby(location_cols)
    .agg(
        Observations=("WL_mbgl", "size"),
        Years=("Year", "nunique"),
        Min_Year=("Year", "min"),
        Max_Year=("Year", "max"),
        Villages=("Village", "nunique"),
        Blocks=("Block", "nunique"),
        Dates=("Date", "nunique")
    )
    .reset_index()
)

print("Potential monitoring locations:")
print(len(station_summary))

print("\nFirst 20:")
print(
    station_summary.head(20).to_string(
        index=False
    )
)

Potential monitoring locations:
41978

First 20:
             State_Standard        District_Standard  Latitude  Longitude  Observations  Years  Min_Year  Max_Year  Villages  Blocks  Dates
Andaman And Nicobar Islands North And Middle Andaman 12.168260  92.766920             1      1      2025      2025         1       1      1
Andaman And Nicobar Islands North And Middle Andaman 12.168280  92.767000            19     19      2004      2024         1       1     19
Andaman And Nicobar Islands North And Middle Andaman 12.186820  92.791870             1      1      2025      2025         1       1      1
Andaman And Nicobar Islands North And Middle Andaman 12.186870  92.791930            10     10      2013      2024         1       1     10
Andaman And Nicobar Islands North And Middle Andaman 12.328020  92.790110            19     19      2004      2024         1       1     19
Andaman And Nicobar Islands North And Middle Andaman 12.328100  92.790020             1      1      2025      2025         1       1      1
Andaman And Nicobar Islands North And Middle Andaman 12.336150  92.919720             1      1      2025      2025         1       1      1
Andaman And Nicobar Islands North And Middle Andaman 12.348750  92.774990            20     20      2004      2025         1       1     20
Andaman And Nicobar Islands North And Middle Andaman 12.364400  92.923680            16     16      2004      2024         1       1     16
Andaman And Nicobar Islands North And Middle Andaman 12.364630  92.923450             1      1      2025      2025         1       1      1
Andaman And Nicobar Islands North And Middle Andaman 12.365120  92.924630             1      1      2025      2025         1       1      1
Andaman And Nicobar Islands North And Middle Andaman 12.365330  92.924800             4      4      2019      2024         1       1      4
Andaman And Nicobar Islands North And Middle Andaman 12.366740  92.922870             1      1      2025      2025         1       1      1
Andaman And Nicobar Islands North And Middle Andaman 12.366740  92.923140            16     16      2004      2024         1       1     16
Andaman And Nicobar Islands North And Middle Andaman 12.367050  92.917620            16     16      2004      2024         1       1     16
Andaman And Nicobar Islands North And Middle Andaman 12.411680  92.762570             1      1      2025      2025         1       1      1
Andaman And Nicobar Islands North And Middle Andaman 12.411790  92.762920            10     10      2013      2024         1       1     10
Andaman And Nicobar Islands North And Middle Andaman 12.494570  92.954150             1      1      2025      2025         1       1      1
Andaman And Nicobar Islands North And Middle Andaman 12.494580  92.954220            21     21      2000      2024         1       1     21
Andaman And Nicobar Islands North And Middle Andaman 12.494581  92.954222             1      1      2001      2001         1       1      1

In [43]:
print("\nLocations with observations in multiple years:")

print(
    (
        station_summary["Years"] > 1
    ).sum()
)

print(
    "\nLocations with 10+ years of observations:"
)

print(
    (
        station_summary["Years"] >= 10
    ).sum()
)

print(
    "\nLocations with 20+ years of observations:"
)

print(
    (
        station_summary["Years"] >= 20
    ).sum()
)

Locations with observations in multiple years:
28401

Locations with 10+ years of observations:
15969

Locations with 20+ years of observations:
7525

In [44]:
multi_village_locations = (
    station_summary[
        station_summary["Villages"] > 1
    ]
)

multi_block_locations = (
    station_summary[
        station_summary["Blocks"] > 1
    ]
)

print(
    "\nCoordinates associated with multiple villages:",
    len(multi_village_locations)
)

print(
    "Coordinates associated with multiple blocks:",
    len(multi_block_locations)
)

print("\nExamples:")
print(
    multi_village_locations
    .head(20)
    .to_string(index=False)
)

Coordinates associated with multiple villages: 368
Coordinates associated with multiple blocks: 255

Examples:
             State_Standard           District_Standard  Latitude  Longitude  Observations  Years  Min_Year  Max_Year  Villages  Blocks  Dates
Andaman And Nicobar Islands              South Andamans 11.537550  92.647950             2      1      2025      2025         2       1      1
             Andhra Pradesh                   Annamayya 14.097778  78.554167             2      1      2001      2001         2       1      2
             Andhra Pradesh                   Annamayya 14.097780  78.554170            14      7      2002      2008         2       1      9
             Andhra Pradesh                     Bapatla 15.993060  80.026390             5      4      2000      2004         2       1      4
             Andhra Pradesh Dr. B.R. Ambedkar Konaseema 16.515000  81.934720            25     11      1997      2008         3       1     19
             Andhra Pradesh Dr. B.R. Ambedkar Konaseema 16.833330  82.033330            32     16      1994      2010         2       1     17
             Andhra Pradesh Dr. B.R. Ambedkar Konaseema 16.833333  82.033333             2      1      2001      2001         2       1      1
             Andhra Pradesh                    Kakinada 17.171670  82.046670            16     15      1994      2010         2       1     15
             Andhra Pradesh                     Kurnool 15.881940  77.345000             5      2      1995      1996         2       1      2
             Andhra Pradesh                     Palnadu 16.307780  79.330560            12     10      1997      2009         2       1     10
             Andhra Pradesh                    Tirupati 13.206670  79.101670             2      1      2010      2010         2       2      1
             Andhra Pradesh                Vizianagaram 18.075300  83.478900            41     30      1994      2025         2       1     30
             Andhra Pradesh                      Y.S.R. 14.460556  78.162500             2      1      2001      2001         2       1      1
             Andhra Pradesh                      Y.S.R. 14.460560  78.162500            21     11      1997      2008         2       1     11
             Andhra Pradesh                      Y.S.R. 14.583330  79.041670            20     10      1998      2008         2       1     10
             Andhra Pradesh                      Y.S.R. 14.583333  79.041667             2      1      2001      2001         2       1      1
                      Bihar                     Bhojpur 25.406940  84.402780             4      3      2023      2025         2       1      3
                      Bihar                     Bhojpur 25.667220  84.361110            13     11      2014      2025         2       1     12
                      Bihar                       Buxar 25.523060  84.273610             8      7      2014      2023         2       1      8
                      Bihar                       Buxar 25.609170  84.342500            11     11      2014      2024         2       1     11

In [45]:
# =========================================================
# STEP 8 — STATION-YEAR OBSERVATION ANALYSIS
# =========================================================

station_cols = [
    "State_Standard",
    "District_Standard",
    "Latitude",
    "Longitude"
]

# ---------------------------------------------------------
# 1. Create station-year summary
# ---------------------------------------------------------

station_year = (
    gw_clean
    .groupby(station_cols + ["Year"])
    .agg(
        Observations=("WL_mbgl", "size"),
        Valid_WL=("WL_mbgl", "count"),
        Mean_WL=("WL_mbgl", "mean"),
        Min_WL=("WL_mbgl", "min"),
        Max_WL=("WL_mbgl", "max"),
        Unique_WL=("WL_mbgl", "nunique")
    )
    .reset_index()
)

# ---------------------------------------------------------
# 2. Overall station-year statistics
# ---------------------------------------------------------

print("=" * 70)
print("STATION-YEAR ANALYSIS")
print("=" * 70)

print(
    f"\nTotal station-year records: "
    f"{len(station_year):,}"
)

print(
    "\nObservations per station-year:"
)

print(
    station_year["Observations"].describe()
)


# ---------------------------------------------------------
# 3. Frequency of observations per station-year
# ---------------------------------------------------------

print(
    "\n" + "=" * 70
)

print(
    "OBSERVATION FREQUENCY"
)

print("=" * 70)

print(
    station_year["Observations"]
    .value_counts()
    .sort_index()
    .head(20)
)


# ---------------------------------------------------------
# 4. Station-years with multiple observations
# ---------------------------------------------------------

multi_obs = station_year[
    station_year["Observations"] > 1
]

print(
    "\n" + "=" * 70
)

print(
    "MULTIPLE OBSERVATIONS PER STATION-YEAR"
)

print("=" * 70)

print(
    f"Station-years with >1 observation: "
    f"{len(multi_obs):,}"
)

print(
    f"Percentage of station-years: "
    f"{len(multi_obs) / len(station_year) * 100:.2f}%"
)


# ---------------------------------------------------------
# 5. Multiple observations with different WL values
# ---------------------------------------------------------

different_measurements = station_year[
    (
        station_year["Observations"] > 1
    )
    &
    (
        station_year["Unique_WL"] > 1
    )
]

print(
    "\n" + "=" * 70
)

print(
    "MULTIPLE DIFFERENT WL VALUES"
)

print("=" * 70)

print(
    f"Station-years with multiple "
    f"different WL values: "
    f"{len(different_measurements):,}"
)

print(
    f"Percentage: "
    f"{len(different_measurements) / len(station_year) * 100:.2f}%"
)


# ---------------------------------------------------------
# 6. Show examples
# ---------------------------------------------------------

if len(different_measurements) > 0:

    print(
        "\nExamples of station-years "
        "with different WL measurements:"
    )

    print(
        different_measurements
        .sort_values(
            "Observations",
            ascending=False
        )
        .head(20)
        .to_string(index=False)
    )


# ---------------------------------------------------------
# 7. Distribution of number of distinct WL values
# ---------------------------------------------------------

print(
    "\n" + "=" * 70
)

print(
    "DISTINCT WL VALUES PER STATION-YEAR"
)

print("=" * 70)

print(
    station_year["Unique_WL"]
    .value_counts()
    .sort_index()
    .head(20)
)

======================================================================
STATION-YEAR ANALYSIS
======================================================================

Total station-year records: 390,667

Observations per station-year:
count    390667.000000
mean          1.009658
std           0.104554
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           4.000000
Name: Observations, dtype: float64

======================================================================
OBSERVATION FREQUENCY
======================================================================
Observations
1    387124
2      3350
3       156
4        37
Name: count, dtype: int64

======================================================================
MULTIPLE OBSERVATIONS PER STATION-YEAR
======================================================================
Station-years with >1 observation: 3,543
Percentage of station-years: 0.91%

======================================================================
MULTIPLE DIFFERENT WL VALUES
======================================================================
Station-years with multiple different WL values: 3,444
Percentage: 0.88%

Examples of station-years with different WL measurements:
State_Standard District_Standard  Latitude  Longitude  Year  Observations  Valid_WL  Mean_WL  Min_WL  Max_WL  Unique_WL
        Punjab           Patiala  30.18472   76.51333  2021             4         4  38.7250   37.40   39.30          4
   Maharashtra         Dharashiv  18.18750   75.99028  1994             4         4  38.3125    4.70   51.00          4
        Punjab           Patiala  30.18472   76.51333  2019             4         4  35.8750   34.50   36.50          4
        Punjab           Patiala  30.18472   76.51333  2012             4         4  27.6050   27.44   27.90          3
        Punjab           Patiala  30.18472   76.51333  2014             4         4  29.2500   29.00   29.70          4
   Maharashtra         Dharashiv  17.80833   76.01667  2000             4         4  43.8000   10.70   69.40          4
        Punjab           Patiala  30.18472   76.51333  2011             4         4  25.9150   25.20   26.65          4
     Karnataka           Raichur  16.27080   77.27080  2017             4         4   6.1950    2.71    9.15          4
     Karnataka           Raichur  16.27080   77.27080  2012             4         4   4.6575    1.49    7.16          4
     Karnataka           Raichur  16.27080   77.27080  2008             4         4   4.6900    1.35    6.52          4
     Karnataka           Raichur  16.27080   77.27080  2011             4         4   5.4375    1.76   12.15          4
     Karnataka           Raichur  16.27080   77.27080  2010             4         4   5.0850    0.70   12.15          4
     Karnataka           Raichur  16.27080   77.27080  2009             4         4   5.0125    2.35    8.32          4
     Karnataka           Raichur  16.27080   77.27080  2007             4         4   5.1875    1.55    8.50          4
     Karnataka           Raichur  16.27080   77.27080  2015             4         4   3.8875    2.04    5.63          4
     Karnataka           Raichur  16.27080   77.27080  2013             4         4   4.8150    1.45    7.05          4
     Karnataka           Raichur  16.27080   77.27080  2023             4         4   4.0750    1.60    5.90          4
Andhra Pradesh           Kurnool  15.88056   77.14333  1999             4         4   1.9625    1.82    2.14          4
Andhra Pradesh           Kurnool  15.88056   77.14333  2000             4         4   1.9625    1.38    2.45          4
     Karnataka           Raichur  16.27080   77.27080  2024             4         4   4.6500    0.60    7.50          4

======================================================================
DISTINCT WL VALUES PER STATION-YEAR
======================================================================
Unique_WL
1    387223
2      3253
3       155
4        36
Name: count, dtype: int64

In [46]:
# =========================================================
# STEP 9 — BUILD STATION × YEAR DATASET
# =========================================================

station_cols = [
    "State_Standard",
    "District_Standard",
    "Latitude",
    "Longitude",
    "Year"
]

station_year_clean = (
    gw_clean
    .groupby(
        station_cols,
        as_index=False
    )
    .agg(
        GW_Mean=("WL_mbgl", "mean"),
        GW_Min=("WL_mbgl", "min"),
        GW_Max=("WL_mbgl", "max"),
        GW_Std=("WL_mbgl", "std"),
        Observation_Count=("WL_mbgl", "count")
    )
)

# ---------------------------------------------------------
# Fill std for stations with only one observation
# ---------------------------------------------------------

station_year_clean["GW_Std"] = (
    station_year_clean["GW_Std"]
    .fillna(0)
)

print("=" * 70)
print("STATION × YEAR DATASET")
print("=" * 70)

print(
    "\nShape:",
    station_year_clean.shape
)

print(
    "\nColumns:"
)

print(
    station_year_clean.columns.tolist()
)

print(
    "\nFirst 10 rows:"
)

print(
    station_year_clean
    .head(10)
    .to_string(index=False)
)

print(
    "\nObservation count distribution:"
)

print(
    station_year_clean[
        "Observation_Count"
    ]
    .value_counts()
    .sort_index()
)

print(
    "\nMissing values:"
)

print(
    station_year_clean.isna().sum()
)

======================================================================
STATION × YEAR DATASET
======================================================================

Shape: (390667, 10)

Columns:
['State_Standard', 'District_Standard', 'Latitude', 'Longitude', 'Year', 'GW_Mean', 'GW_Min', 'GW_Max', 'GW_Std', 'Observation_Count']

First 10 rows:
             State_Standard        District_Standard  Latitude  Longitude  Year  GW_Mean  GW_Min  GW_Max  GW_Std  Observation_Count
Andaman And Nicobar Islands North And Middle Andaman  12.16826   92.76692  2025     1.02    1.02    1.02     0.0                  1
Andaman And Nicobar Islands North And Middle Andaman  12.16828   92.76700  2004     5.30    5.30    5.30     0.0                  1
Andaman And Nicobar Islands North And Middle Andaman  12.16828   92.76700  2005     1.54    1.54    1.54     0.0                  1
Andaman And Nicobar Islands North And Middle Andaman  12.16828   92.76700  2006     0.60    0.60    0.60     0.0                  1
Andaman And Nicobar Islands North And Middle Andaman  12.16828   92.76700  2007     3.77    3.77    3.77     0.0                  1
Andaman And Nicobar Islands North And Middle Andaman  12.16828   92.76700  2008     0.10    0.10    0.10     0.0                  1
Andaman And Nicobar Islands North And Middle Andaman  12.16828   92.76700  2009     1.16    1.16    1.16     0.0                  1
Andaman And Nicobar Islands North And Middle Andaman  12.16828   92.76700  2010     2.89    2.89    2.89     0.0                  1
Andaman And Nicobar Islands North And Middle Andaman  12.16828   92.76700  2011     0.39    0.39    0.39     0.0                  1
Andaman And Nicobar Islands North And Middle Andaman  12.16828   92.76700  2012     1.33    1.33    1.33     0.0                  1

Observation count distribution:
Observation_Count
1    387125
2      3349
3       156
4        37
Name: count, dtype: int64

Missing values:
State_Standard       0
District_Standard    0
Latitude             0
Longitude            0
Year                 0
GW_Mean              0
GW_Min               0
GW_Max               0
GW_Std               0
Observation_Count    0
dtype: int64

In [47]:
# =========================================================
# STEP 10 — DISTRICT × YEAR GROUNDWATER AGGREGATION
# =========================================================

district_year_gw = (
    station_year_clean
    .groupby(
        [
            "State_Standard",
            "District_Standard",
            "Year"
        ],
        as_index=False
    )
    .agg(
        GW_Mean=("GW_Mean", "mean"),
        GW_Median=("GW_Mean", "median"),
        GW_Min=("GW_Mean", "min"),
        GW_Max=("GW_Mean", "max"),
        GW_Std=("GW_Mean", "std"),
        GW_Q25=("GW_Mean", lambda x: x.quantile(0.25)),
        GW_Q75=("GW_Mean", lambda x: x.quantile(0.75)),
        Station_Count=("Latitude", "count"),
        Total_Observations=("Observation_Count", "sum")
    )
)

# ---------------------------------------------------------
# Single-station districts have no spatial std
# ---------------------------------------------------------

district_year_gw["GW_Std"] = (
    district_year_gw["GW_Std"]
    .fillna(0)
)

print("=" * 70)
print("DISTRICT × YEAR GROUNDWATER DATASET")
print("=" * 70)

print(
    "\nShape:",
    district_year_gw.shape
)

print(
    "\nColumns:"
)

print(
    district_year_gw.columns.tolist()
)

print(
    "\nFirst 15 rows:"
)

print(
    district_year_gw
    .head(15)
    .to_string(index=False)
)

print(
    "\nMissing values:"
)

print(
    district_year_gw.isna().sum()
)

print(
    "\nYear range:"
)

print(
    district_year_gw["Year"].min(),
    "to",
    district_year_gw["Year"].max()
)

print(
    "\nStation count statistics:"
)

print(
    district_year_gw["Station_Count"].describe()
)

print(
    "\nDistrict-year records by year:"
)

print(
    district_year_gw
    .groupby("Year")
    .size()
    .tail(15)
)

======================================================================
DISTRICT × YEAR GROUNDWATER DATASET
======================================================================

Shape: (20559, 12)

Columns:
['State_Standard', 'District_Standard', 'Year', 'GW_Mean', 'GW_Median', 'GW_Min', 'GW_Max', 'GW_Std', 'GW_Q25', 'GW_Q75', 'Station_Count', 'Total_Observations']

First 15 rows:
             State_Standard        District_Standard  Year  GW_Mean  GW_Median  GW_Min  GW_Max   GW_Std  GW_Q25  GW_Q75  Station_Count  Total_Observations
Andaman And Nicobar Islands North And Middle Andaman  2000 1.840000      1.430    0.22    4.06 1.423528  0.8600  2.7250              7                   7
Andaman And Nicobar Islands North And Middle Andaman  2001 2.678571      2.780    1.01    4.26 1.138807  1.9400  3.4100              7                   7
Andaman And Nicobar Islands North And Middle Andaman  2003 1.980000      1.700    0.80    3.60 0.970636  1.4700  2.4100              7                   7
Andaman And Nicobar Islands North And Middle Andaman  2004 3.367037      3.220    1.37    8.96 1.435971  2.4650  3.7550             27                  27
Andaman And Nicobar Islands North And Middle Andaman  2005 2.334444      1.880    0.87    7.83 1.486654  1.3800  2.8350             27                  27
Andaman And Nicobar Islands North And Middle Andaman  2006 1.168889      1.100    0.20    2.97 0.551022  0.9000  1.3600             27                  27
Andaman And Nicobar Islands North And Middle Andaman  2007 2.735185      2.300    0.90    6.86 1.245445  1.8600  3.5200             27                  27
Andaman And Nicobar Islands North And Middle Andaman  2008 0.507778      0.400    0.05    2.00 0.468790  0.2000  0.5200             27                  27
Andaman And Nicobar Islands North And Middle Andaman  2009 1.548750      1.535    0.10    3.64 1.004400  0.5450  2.0850             24                  24
Andaman And Nicobar Islands North And Middle Andaman  2010 2.247037      2.320    0.40    4.03 0.720597  1.8000  2.5150             27                  27
Andaman And Nicobar Islands North And Middle Andaman  2011 1.095833      0.920    0.01    3.26 0.853636  0.4575  1.7600             24                  24
Andaman And Nicobar Islands North And Middle Andaman  2012 2.373333      2.330    0.36    4.50 1.178121  1.2650  3.2000             27                  27
Andaman And Nicobar Islands North And Middle Andaman  2013 1.346061      0.930    0.20    4.47 1.052776  0.4200  2.0500             33                  33
Andaman And Nicobar Islands North And Middle Andaman  2014 2.833056      2.725    0.42    5.87 1.312959  1.9925  3.3925             36                  36
Andaman And Nicobar Islands North And Middle Andaman  2015 2.296286      2.070    0.05    7.53 1.428541  1.5600  2.6650             35                  35

Missing values:
State_Standard        0
District_Standard     0
Year                  0
GW_Mean               0
GW_Median             0
GW_Min                0
GW_Max                0
GW_Std                0
GW_Q25                0
GW_Q75                0
Station_Count         0
Total_Observations    0
dtype: int64

Year range:
1994 to 2025

Station count statistics:
count    20559.000000
mean        19.002237
std         17.380143
min          1.000000
25%          7.000000
50%         14.000000
75%         25.000000
max        193.000000
Name: Station_Count, dtype: float64

District-year records by year:
Year
2011    675
2012    673
2013    680
2014    675
2015    671
2016    684
2017    671
2018    672
2019    675
2020    464
2021    506
2022    681
2023    685
2024    706
2025    698
dtype: int64

In [48]:
# =========================================================
# STEP 11 — GROUNDWATER TEMPORAL FEATURES
# =========================================================

import numpy as np
import pandas as pd


# ---------------------------------------------------------
# Helper: calculate linear trend
# ---------------------------------------------------------

def calculate_trend(group):
    """
    Linear trend of groundwater level against year.
    Positive slope  -> groundwater depth increasing
    Negative slope  -> groundwater depth decreasing
    """

    group = group.dropna(
        subset=["Year", "GW_Mean"]
    )

    if len(group) < 2:
        return np.nan

    x = group["Year"].to_numpy()
    y = group["GW_Mean"].to_numpy()

    return np.polyfit(x, y, 1)[0]


# ---------------------------------------------------------
# Feature extraction helper
# ---------------------------------------------------------

def period_features(df, start_year, end_year, prefix):

    period = df[
        df["Year"].between(
            start_year,
            end_year
        )
    ].copy()

    grouped = (
        period
        .groupby(
            [
                "State_Standard",
                "District_Standard"
            ]
        )
    )

    features = grouped.agg(
        **{
            f"{prefix}_Mean": (
                "GW_Mean",
                "mean"
            ),
            f"{prefix}_Median": (
                "GW_Median",
                "mean"
            ),
            f"{prefix}_Std": (
                "GW_Mean",
                "std"
            ),
            f"{prefix}_Min": (
                "GW_Mean",
                "min"
            ),
            f"{prefix}_Max": (
                "GW_Mean",
                "max"
            ),
            f"{prefix}_Years_Available": (
                "Year",
                "nunique"
            ),
            f"{prefix}_Avg_Stations": (
                "Station_Count",
                "mean"
            )
        }
    ).reset_index()

    # Linear trend
    trend = (
        grouped
        .apply(
            calculate_trend,
            include_groups=False
        )
        .reset_index(
            name=f"{prefix}_Trend"
        )
    )

    features = features.merge(
        trend,
        on=[
            "State_Standard",
            "District_Standard"
        ],
        how="left"
    )

    return features


# =========================================================
# CREATE PERIOD FEATURES
# =========================================================

gw_1994_2025 = period_features(
    district_year_gw,
    1994,
    2025,
    "GW_1994_2025"
)

gw_2015_2025 = period_features(
    district_year_gw,
    2015,
    2025,
    "GW_2015_2025"
)

gw_2021_2025 = period_features(
    district_year_gw,
    2021,
    2025,
    "GW_2021_2025"
)


# =========================================================
# LATEST 2025 FEATURES
# =========================================================

gw_2025 = (
    district_year_gw[
        district_year_gw["Year"] == 2025
    ][
        [
            "State_Standard",
            "District_Standard",
            "GW_Mean",
            "GW_Median",
            "GW_Min",
            "GW_Max",
            "GW_Std",
            "Station_Count",
            "Total_Observations"
        ]
    ]
    .rename(
        columns={
            "GW_Mean": "GW_Latest_2025",
            "GW_Median": "GW_Latest_Median_2025",
            "GW_Min": "GW_Latest_Min_2025",
            "GW_Max": "GW_Latest_Max_2025",
            "GW_Std": "GW_Latest_Std_2025",
            "Station_Count": "GW_Stations_2025",
            "Total_Observations": "GW_Observations_2025"
        }
    )
)


# =========================================================
# COMBINE FEATURES
# =========================================================

gw_features = gw_1994_2025.merge(
    gw_2015_2025,
    on=[
        "State_Standard",
        "District_Standard"
    ],
    how="outer"
)

gw_features = gw_features.merge(
    gw_2021_2025,
    on=[
        "State_Standard",
        "District_Standard"
    ],
    how="outer"
)

gw_features = gw_features.merge(
    gw_2025,
    on=[
        "State_Standard",
        "District_Standard"
    ],
    how="outer"
)


# =========================================================
# EARLY VS RECENT CHANGE
# =========================================================

# Earlier 5-year period
gw_2015_2019 = (
    district_year_gw[
        district_year_gw["Year"].between(
            2015,
            2019
        )
    ]
    .groupby(
        [
            "State_Standard",
            "District_Standard"
        ]
    )["GW_Mean"]
    .mean()
    .reset_index(
        name="GW_Mean_2015_2019"
    )
)

# Recent 5-year period
gw_2021_2025_mean = (
    district_year_gw[
        district_year_gw["Year"].between(
            2021,
            2025
        )
    ]
    .groupby(
        [
            "State_Standard",
            "District_Standard"
        ]
    )["GW_Mean"]
    .mean()
    .reset_index(
        name="GW_Mean_2021_2025"
    )
)

gw_features = gw_features.merge(
    gw_2015_2019,
    on=[
        "State_Standard",
        "District_Standard"
    ],
    how="left"
)

gw_features = gw_features.merge(
    gw_2021_2025_mean,
    on=[
        "State_Standard",
        "District_Standard"
    ],
    how="left"
)

gw_features["GW_Recent_vs_Early_Change"] = (
    gw_features["GW_Mean_2021_2025"]
    - gw_features["GW_Mean_2015_2019"]
)


# =========================================================
# CLEAN FEATURE TABLE
# =========================================================

gw_features = (
    gw_features
    .replace([np.inf, -np.inf], np.nan)
    .reset_index(drop=True)
)


# =========================================================
# REPORT
# =========================================================

print("=" * 70)
print("GROUNDWATER TEMPORAL FEATURE TABLE")
print("=" * 70)

print(
    "\nShape:",
    gw_features.shape
)

print(
    "\nNumber of districts:",
    len(gw_features)
)

print(
    "\nColumns:"
)

print(
    gw_features.columns.tolist()
)

print(
    "\nMissing values:"
)

print(
    gw_features.isna().sum()
)

print(
    "\nFirst 10 districts:"
)

print(
    gw_features
    .head(10)
    .to_string(index=False)
)

======================================================================
GROUNDWATER TEMPORAL FEATURE TABLE
======================================================================

Shape: (717, 36)

Number of districts: 717

Columns:
['State_Standard', 'District_Standard', 'GW_1994_2025_Mean', 'GW_1994_2025_Median', 'GW_1994_2025_Std', 'GW_1994_2025_Min', 'GW_1994_2025_Max', 'GW_1994_2025_Years_Available', 'GW_1994_2025_Avg_Stations', 'GW_1994_2025_Trend', 'GW_2015_2025_Mean', 'GW_2015_2025_Median', 'GW_2015_2025_Std', 'GW_2015_2025_Min', 'GW_2015_2025_Max', 'GW_2015_2025_Years_Available', 'GW_2015_2025_Avg_Stations', 'GW_2015_2025_Trend', 'GW_2021_2025_Mean', 'GW_2021_2025_Median', 'GW_2021_2025_Std', 'GW_2021_2025_Min', 'GW_2021_2025_Max', 'GW_2021_2025_Years_Available', 'GW_2021_2025_Avg_Stations', 'GW_2021_2025_Trend', 'GW_Latest_2025', 'GW_Latest_Median_2025', 'GW_Latest_Min_2025', 'GW_Latest_Max_2025', 'GW_Latest_Std_2025', 'GW_Stations_2025', 'GW_Observations_2025', 'GW_Mean_2015_2019', 'GW_Mean_2021_2025', 'GW_Recent_vs_Early_Change']

Missing values:
State_Standard                   0
District_Standard                0
GW_1994_2025_Mean                0
GW_1994_2025_Median              0
GW_1994_2025_Std                 4
GW_1994_2025_Min                 0
GW_1994_2025_Max                 0
GW_1994_2025_Years_Available     0
GW_1994_2025_Avg_Stations        0
GW_1994_2025_Trend               4
GW_2015_2025_Mean                5
GW_2015_2025_Median              5
GW_2015_2025_Std                 9
GW_2015_2025_Min                 5
GW_2015_2025_Max                 5
GW_2015_2025_Years_Available     5
GW_2015_2025_Avg_Stations        5
GW_2015_2025_Trend               9
GW_2021_2025_Mean                7
GW_2021_2025_Median              7
GW_2021_2025_Std                10
GW_2021_2025_Min                 7
GW_2021_2025_Max                 7
GW_2021_2025_Years_Available     7
GW_2021_2025_Avg_Stations        7
GW_2021_2025_Trend              10
GW_Latest_2025                  19
GW_Latest_Median_2025           19
GW_Latest_Min_2025              19
GW_Latest_Max_2025              19
GW_Latest_Std_2025              19
GW_Stations_2025                19
GW_Observations_2025            19
GW_Mean_2015_2019               29
GW_Mean_2021_2025                7
GW_Recent_vs_Early_Change       31
dtype: int64

First 10 districts:
             State_Standard           District_Standard  GW_1994_2025_Mean  GW_1994_2025_Median  GW_1994_2025_Std  GW_1994_2025_Min  GW_1994_2025_Max  GW_1994_2025_Years_Available  GW_1994_2025_Avg_Stations  GW_1994_2025_Trend  GW_2015_2025_Mean  GW_2015_2025_Median  GW_2015_2025_Std  GW_2015_2025_Min  GW_2015_2025_Max  GW_2015_2025_Years_Available  GW_2015_2025_Avg_Stations  GW_2015_2025_Trend  GW_2021_2025_Mean  GW_2021_2025_Median  GW_2021_2025_Std  GW_2021_2025_Min  GW_2021_2025_Max  GW_2021_2025_Years_Available  GW_2021_2025_Avg_Stations  GW_2021_2025_Trend  GW_Latest_2025  GW_Latest_Median_2025  GW_Latest_Min_2025  GW_Latest_Max_2025  GW_Latest_Std_2025  GW_Stations_2025  GW_Observations_2025  GW_Mean_2015_2019  GW_Mean_2021_2025  GW_Recent_vs_Early_Change
Andaman And Nicobar Islands    North And Middle Andaman           1.936931             1.756087          0.788586          0.507778          3.367037                            23                  28.695652           -0.018940           1.832605             1.646667          0.810260          0.888421          3.031579                           9.0                  37.000000           -0.028107           1.846118              1.74125          0.973033          0.926316          3.031579                           4.0                      38.00            0.157447        1.187105                  0.965                0.14                4.00            0.879880              38.0                  38.0           1.821794           1.846118                   0.024325
Andaman And Nicobar Islands              South Andamans           2.150800             1.872917          0.676711          0.642903          3.120000                            24                  49.083333           -0.012826           2.106426             1.820000          0.550671          1.182639          2.813699                           9.0                  71.333333           -0.021978           2.124466              1.84250          0.557966          1.580000          2.813699                           4.0                      72.00           -0.010325        1.580000                  1.270                0.06                6.60            1.277163              71.0                  72.0           2.091994           2.124466                   0.032473
             Andhra Pradesh       Alluri Sitharama Raju           6.193789             5.831667          1.073014          3.158485          8.424062                            30                  30.000000           -0.079408           5.240808             4.718333          0.845355          3.158485          5.976190                           9.0                  39.555556           -0.114078           4.817883              4.28000          1.187833          3.158485          5.976190                           4.0                      39.00           -0.497710        3.158485                  2.970                0.30                8.42            2.080439              33.0                  33.0           5.579149           4.817883                  -0.761266
             Andhra Pradesh                  Anakapalli           4.735774             4.385667          0.928691          3.158750          6.654211                            30                  19.166667           -0.040468           4.204009             3.679444          0.813417          3.355000          5.441667                           9.0                  21.333333            0.001856           4.003646              3.50000          0.973795          3.355000          5.441667                           4.0                      23.00            0.199708        3.459583                  3.200                0.85                8.93            1.916098              24.0                  24.0           4.364300           4.003646                  -0.360654
             Andhra Pradesh               Ananthapuramu           8.552747             7.605000          2.532930          4.454000         14.596047                            31                  26.483871           -0.054613           7.906241             6.613500          2.476070          5.100000         13.141071                          10.0                  14.600000            0.242275           8.749492              5.63125          3.554729          5.100000         13.141071                           4.0                      24.50            2.094033        9.964038                  6.275                1.24               43.62           10.370359              26.0                  29.0           7.692889           8.749492                   1.056603
             Andhra Pradesh                   Annamayya          10.350728             8.783125          3.563539          4.850000         19.587273                            32                  25.062500           -0.005546          10.067060             8.279091          3.937561          4.850000         17.472222                          11.0                  19.181818            0.349887          10.585371              8.54000          3.897242          5.895000         15.776316                           5.0                      26.60            1.287348       12.496081                  8.600                1.89               48.20            9.970371              37.0                  38.0          10.162162          10.585371                   0.423210
             Andhra Pradesh                     Bapatla           3.572228             3.050484          0.706334          2.200000          5.187391                            31                  16.935484           -0.017966           3.462999             2.921500          0.722266          2.200000          4.316667                          10.0                  21.200000           -0.081741           3.172979              2.85875          0.603997          2.806667          4.076190                           4.0                      23.00            0.090380        2.806667                  2.535                0.05                7.39            1.763580              24.0                  24.0           3.947616           3.172979                  -0.774637
             Andhra Pradesh                    Chittoor           9.298007             8.546774          2.893304          3.881250         16.155116                            31                  25.516129           -0.029031           8.549177             7.071000          3.164480          3.881250         14.265517                          10.0                  18.300000            0.439869           9.810537              5.67500          4.886190          3.881250         14.265517                           4.0                      25.75            3.486505       13.334667                  5.600                0.55              116.00           23.955957              30.0                  30.0           7.734924           9.810537                   2.075613
             Andhra Pradesh Dr. B.R. Ambedkar Konaseema           3.415375             2.759944          0.468873          2.579000          4.474643                            30                  20.133333           -0.002317           3.522127             2.663333          0.433552          2.920000          4.446875                           9.0                  30.000000            0.024835           3.554864              2.53500          0.646351          2.920000          4.446875                           4.0                      30.75            0.212462        3.322581                  2.340                0.67               25.04            4.269641              31.0                  32.0           3.495937           3.554864                   0.058927
             Andhra Pradesh               East Godavari           6.975012             4.632258          1.996153          3.493478         11.058261                            31                  18.967742           -0.087808           5.580493             3.714000          1.438086          3.493478          7.413043                          10.0                  20.500000           -0.093174           5.100096              3.28000          1.651444          3.493478          7.413043                           4.0                      22.50           -0.669193        4.773409                  2.520                0.57               33.64            6.868057              22.0                  23.0           5.690909           5.100096                  -0.590813

In [49]:
# =========================================================
# STEP 12 — VALIDATE GROUNDWATER TEMPORAL FEATURES
# =========================================================

trend_cols = [
    "GW_1994_2025_Trend",
    "GW_2015_2025_Trend",
    "GW_2021_2025_Trend"
]

change_cols = [
    "GW_Recent_vs_Early_Change"
]

print("=" * 70)
print("GROUNDWATER TEMPORAL FEATURE VALIDATION")
print("=" * 70)


# ---------------------------------------------------------
# 1. TREND DISTRIBUTIONS
# ---------------------------------------------------------

print("\n" + "=" * 70)
print("TREND DISTRIBUTIONS")
print("=" * 70)

for col in trend_cols:

    print(f"\n{col}")

    print(
        gw_features[col]
        .describe()
    )


# ---------------------------------------------------------
# 2. MOST POSITIVE / NEGATIVE LONG-TERM TRENDS
# ---------------------------------------------------------

print("\n" + "=" * 70)
print("EXTREME LONG-TERM TRENDS")
print("=" * 70)

cols_to_show = [
    "State_Standard",
    "District_Standard",
    "GW_1994_2025_Years_Available",
    "GW_1994_2025_Mean",
    "GW_1994_2025_Trend"
]

print("\nMost positive trends:")

print(
    gw_features
    .sort_values(
        "GW_1994_2025_Trend",
        ascending=False
    )
    [cols_to_show]
    .head(15)
    .to_string(index=False)
)

print("\nMost negative trends:")

print(
    gw_features
    .sort_values(
        "GW_1994_2025_Trend",
        ascending=True
    )
    [cols_to_show]
    .head(15)
    .to_string(index=False)
)


# ---------------------------------------------------------
# 3. RECENT VS EARLY CHANGE
# ---------------------------------------------------------

print("\n" + "=" * 70)
print("RECENT VS EARLY CHANGE")
print("=" * 70)

print(
    gw_features[
        "GW_Recent_vs_Early_Change"
    ].describe()
)

cols_to_show = [
    "State_Standard",
    "District_Standard",
    "GW_Mean_2015_2019",
    "GW_Mean_2021_2025",
    "GW_Recent_vs_Early_Change"
]

print("\nLargest positive changes:")

print(
    gw_features
    .sort_values(
        "GW_Recent_vs_Early_Change",
        ascending=False
    )
    [cols_to_show]
    .head(15)
    .to_string(index=False)
)

print("\nLargest negative changes:")

print(
    gw_features
    .sort_values(
        "GW_Recent_vs_Early_Change",
        ascending=True
    )
    [cols_to_show]
    .head(15)
    .to_string(index=False)
)


# ---------------------------------------------------------
# 4. HISTORICAL COVERAGE
# ---------------------------------------------------------

print("\n" + "=" * 70)
print("HISTORICAL COVERAGE")
print("=" * 70)

for col in [
    "GW_1994_2025_Years_Available",
    "GW_2015_2025_Years_Available",
    "GW_2021_2025_Years_Available"
]:

    print(f"\n{col}")

    print(
        gw_features[col]
        .describe()
    )


# ---------------------------------------------------------
# 5. DISTRICTS WITH VERY LOW COVERAGE
# ---------------------------------------------------------

print("\n" + "=" * 70)
print("LOW COVERAGE DISTRICTS")
print("=" * 70)

low_coverage = gw_features[
    (
        gw_features[
            "GW_2015_2025_Years_Available"
        ] < 3
    )
]

print(
    f"\nDistricts with fewer than 3 "
    f"years during 2015–2025: "
    f"{len(low_coverage)}"
)

if len(low_coverage) > 0:

    print(
        low_coverage[
            [
                "State_Standard",
                "District_Standard",
                "GW_2015_2025_Years_Available",
                "GW_2021_2025_Years_Available",
                "GW_1994_2025_Years_Available"
            ]
        ]
        .sort_values(
            "GW_2015_2025_Years_Available"
        )
        .head(30)
        .to_string(index=False)
    )


# ---------------------------------------------------------
# 6. 2025 COVERAGE
# ---------------------------------------------------------

print("\n" + "=" * 70)
print("2025 COVERAGE")
print("=" * 70)

missing_2025 = gw_features[
    gw_features["GW_Latest_2025"].isna()
]

print(
    f"\nDistricts without 2025 data: "
    f"{len(missing_2025)}"
)

if len(missing_2025) > 0:

    print(
        missing_2025[
            [
                "State_Standard",
                "District_Standard",
                "GW_2015_2025_Years_Available",
                "GW_2021_2025_Years_Available"
            ]
        ]
        .to_string(index=False)
    )


# ---------------------------------------------------------
# 7. INFINITE VALUES
# ---------------------------------------------------------

print("\n" + "=" * 70)
print("INVALID VALUES")
print("=" * 70)

numeric_cols = (
    gw_features
    .select_dtypes(
        include=np.number
    )
    .columns
)

inf_count = np.isinf(
    gw_features[numeric_cols]
).sum().sum()

print(
    "Total infinite values:",
    inf_count
)

print(
    "Total NaN values:",
    gw_features.isna().sum().sum()
)

======================================================================
GROUNDWATER TEMPORAL FEATURE VALIDATION
======================================================================

======================================================================
TREND DISTRIBUTIONS
======================================================================

GW_1994_2025_Trend
count    713.000000
mean       0.098809
std        1.048550
min       -6.886364
25%       -0.047812
50%       -0.005904
75%        0.037207
max       21.285000
Name: GW_1994_2025_Trend, dtype: float64

GW_2015_2025_Trend
count    708.000000
mean       0.025239
std        1.120643
min       -6.886364
25%       -0.211406
50%       -0.075246
75%        0.035627
max       21.285000
Name: GW_2015_2025_Trend, dtype: float64

GW_2021_2025_Trend
count    707.000000
mean       0.157725
std        1.430479
min      -12.821333
25%       -0.188540
50%        0.070367
75%        0.414160
max       21.285000
Name: GW_2021_2025_Trend, dtype: float64

======================================================================
EXTREME LONG-TERM TRENDS
======================================================================

Most positive trends:
   State_Standard District_Standard  GW_1994_2025_Years_Available  GW_1994_2025_Mean  GW_1994_2025_Trend
      Uttarakhand      Rudra Prayag                             2          34.742500           21.285000
      Uttarakhand           Chamoli                             2          19.427308           13.285385
 Himachal Pradesh            Chamba                             2           9.350000            4.100000
      Uttarakhand       Pithoragarh                             2          12.766909            3.970182
      Uttarakhand     Tehri Garhwal                             3          39.092359            3.677000
 Himachal Pradesh          Bilaspur                             2          13.633056            2.882778
         Nagaland          Tseminyu                             2           8.613000            2.546000
          Mizoram           Kolasib                             2           1.495000            2.190000
Jammu And Kashmir            Poonch                             3          10.888333            2.120000
          Mizoram          Serchhip                             2           0.775000            1.550000
           Punjab           Sangrur                            32          21.706890            1.258987
        Rajasthan            Jaipur                            32          39.302760            1.256170
        Rajasthan   Kotputli-Behror                            31          37.410892            1.210446
           Punjab           Barnala                            32          23.232122            1.138268
          Haryana       Kurukshetra                            32          25.996661            1.118862

Most negative trends:
   State_Standard   District_Standard  GW_1994_2025_Years_Available  GW_1994_2025_Mean  GW_1994_2025_Trend
      Uttarakhand              Almora                             2          14.793182           -6.886364
      Uttarakhand           Bageshwar                             2           7.553333           -2.253333
Jammu And Kashmir           Ganderbal                             3           6.343333           -1.710000
Arunachal Pradesh Lower Dibang Valley                             4           8.630000           -0.835294
          Manipur           Kangpokpi                             2           2.507500           -0.785000
        Rajasthan             Bikaner                            32          43.851957           -0.774319
         Nagaland               Wokha                             7           8.570714           -0.516330
        Rajasthan             Jodhpur                            32          20.289609           -0.435201
Jammu And Kashmir           Bandipora                             2           1.603333           -0.393333
         Nagaland                Phek                             2           3.519286           -0.321429
       Tamil Nadu             Vellore                            30          13.701230           -0.318018
         Nagaland               Peren                             8           8.137917           -0.282736
Jammu And Kashmir             Pulwama                             9          10.102222           -0.264463
       Tamil Nadu        The Nilgiris                            29           9.177093           -0.251090
    Uttar Pradesh              Etawah                            31          15.699533           -0.229236

======================================================================
RECENT VS EARLY CHANGE
======================================================================
count    686.000000
mean      -0.485552
std        2.737352
min       -9.975829
25%       -1.634637
50%       -0.661388
75%        0.094826
max       43.475399
Name: GW_Recent_vs_Early_Change, dtype: float64

Largest positive changes:
   State_Standard District_Standard  GW_Mean_2015_2019  GW_Mean_2021_2025  GW_Recent_vs_Early_Change
        Rajasthan           Phalodi          33.255462          76.730860                  43.475399
        Rajasthan  Jodhpur (Gramin)          23.089221          35.128567                  12.039346
           Punjab           Barnala          30.869000          40.810572                   9.941572
        Rajasthan  Khairthal-Tijara          32.641286          41.895756                   9.254470
        Rajasthan            Nagaur          44.292467          53.434070                   9.141604
        Rajasthan   Kotputli-Behror          45.757776          54.167766                   8.409989
        Rajasthan          Sanchore          32.553076          40.657657                   8.104581
          Haryana         Fatehabad          13.129153          21.167210                   8.038057
        Rajasthan     Neem Ka Thana          27.440500          35.085250                   7.644750
        Rajasthan             Alwar          22.609933          30.128766                   7.518832
        Rajasthan  Didwana-Kuchaman          29.642552          36.733339                   7.090787
           Punjab           Sangrur          32.126292          38.991510                   6.865218
        Rajasthan         Jhunjhunu          52.934691          59.517194                   6.582503
Jammu And Kashmir           Pulwama           4.285000          10.518000                   6.233000
    Uttar Pradesh           Sambhal          12.923182          18.700867                   5.777685

Largest negative changes:
State_Standard District_Standard  GW_Mean_2015_2019  GW_Mean_2021_2025  GW_Recent_vs_Early_Change
         Delhi             South          46.858083          36.882254                  -9.975829
      Nagaland             Wokha          12.472500           3.240000                  -9.232500
         Delhi        South East          20.965300          14.994300                  -5.971000
    Tamil Nadu        Perambalur          10.599259           4.694063                  -5.905196
         Delhi        South West          14.750271           9.076182                  -5.674089
       Haryana      Mahendragarh          36.058198          30.745883                  -5.312315
    Tamil Nadu        Viluppuram           9.291610           4.022066                  -5.269543
    Tamil Nadu           Vellore          11.268306           6.030909                  -5.237396
     Telangana        Wanaparthy          12.537000           7.443750                  -5.093250
       Gujarat             Botad          16.021508          11.029341                  -4.992167
    Tamil Nadu             Erode          12.105023           7.278483                  -4.826540
       Gujarat         Porbandar          13.908385           9.128920                  -4.779465
    Tamil Nadu      Virudhunagar           8.760242           4.261277                  -4.498965
Andhra Pradesh            Y.S.R.          13.634664           9.142036                  -4.492627
    Tamil Nadu      Kallakurichi           9.101209           4.635041                  -4.466168

======================================================================
HISTORICAL COVERAGE
======================================================================

GW_1994_2025_Years_Available
count    717.000000
mean      28.673640
std        6.561232
min        1.000000
25%       30.000000
50%       31.000000
75%       32.000000
max       32.000000
Name: GW_1994_2025_Years_Available, dtype: float64

GW_2015_2025_Years_Available
count    712.000000
mean       9.990169
std        1.808299
min        1.000000
25%       10.000000
50%       11.000000
75%       11.000000
max       11.000000
Name: GW_2015_2025_Years_Available, dtype: float64

GW_2021_2025_Years_Available
count    710.000000
mean       4.614085
std        0.698840
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000
Name: GW_2021_2025_Years_Available, dtype: float64

======================================================================
LOW COVERAGE DISTRICTS
======================================================================

Districts with fewer than 3 years during 2015–2025: 18
   State_Standard        District_Standard  GW_2015_2025_Years_Available  GW_2021_2025_Years_Available  GW_1994_2025_Years_Available
     Chhattisgarh Dakshin Bastar Dantewada                           1.0                           NaN                            16
          Mizoram                 Champhai                           1.0                           1.0                             1
          Mizoram                    Mamit                           1.0                           1.0                             1
          Mizoram                Lawngtlai                           1.0                           1.0                             1
Jammu And Kashmir                Bandipora                           2.0                           2.0                             2
          Manipur                Kangpokpi                           2.0                           2.0                             2
 Himachal Pradesh                   Chamba                           2.0                           2.0                             2
 Himachal Pradesh                 Bilaspur                           2.0                           2.0                             2
          Mizoram                  Kolasib                           2.0                           2.0                             2
          Manipur                 Senapati                           2.0                           2.0                             2
          Mizoram                 Serchhip                           2.0                           2.0                             2
         Nagaland                     Phek                           2.0                           2.0                             2
         Nagaland                 Tseminyu                           2.0                           2.0                             2
      Uttarakhand                   Almora                           2.0                           2.0                             2
      Uttarakhand                Bageshwar                           2.0                           2.0                             2
      Uttarakhand                  Chamoli                           2.0                           2.0                             2
      Uttarakhand              Pithoragarh                           2.0                           2.0                             2
      Uttarakhand             Rudra Prayag                           2.0                           2.0                             2

======================================================================
2025 COVERAGE
======================================================================

Districts without 2025 data: 19
State_Standard        District_Standard  GW_2015_2025_Years_Available  GW_2021_2025_Years_Available
         Assam  South Salmara Mancachar                           NaN                           NaN
  Chhattisgarh                  Bijapur                           NaN                           NaN
  Chhattisgarh Dakshin Bastar Dantewada                           1.0                           NaN
  Chhattisgarh               Narayanpur                           3.0                           NaN
  Chhattisgarh                    Sukma                           NaN                           NaN
       Haryana                Faridabad                          10.0                           4.0
       Haryana                  Jhajjar                          10.0                           4.0
       Haryana             Mahendragarh                          10.0                           4.0
       Haryana                      Nuh                          10.0                           4.0
       Haryana                   Palwal                          10.0                           4.0
       Haryana                   Rewari                          10.0                           4.0
       Haryana                   Rohtak                          10.0                           4.0
       Haryana                  Sonipat                          10.0                           4.0
     Karnataka                Bagalkote                           9.0                           3.0
     Karnataka          Bengaluru Rural                           9.0                           3.0
     Karnataka               Vijayapura                           9.0                           3.0
       Manipur                  Jiribam                           NaN                           NaN
     Meghalaya       East Jaintia Hills                           NaN                           NaN
 Uttar Pradesh                 Fatehpur                          10.0                           4.0

======================================================================
INVALID VALUES
======================================================================
Total infinite values: 0
Total NaN values: 318

In [50]:
# =========================================================
# STEP 13 — INSPECT EXTREME GROUNDWATER TRENDS
# =========================================================

# ---------------------------------------------------------
# Districts with suspiciously large long-term trends
# ---------------------------------------------------------

top_long_term = (
    gw_features
    .dropna(subset=["GW_1994_2025_Trend"])
    .sort_values(
        "GW_1994_2025_Trend",
        ascending=False
    )
    .head(10)
    [
        [
            "State_Standard",
            "District_Standard",
            "GW_1994_2025_Years_Available",
            "GW_1994_2025_Trend"
        ]
    ]
)

bottom_long_term = (
    gw_features
    .dropna(subset=["GW_1994_2025_Trend"])
    .sort_values(
        "GW_1994_2025_Trend",
        ascending=True
    )
    .head(10)
    [
        [
            "State_Standard",
            "District_Standard",
            "GW_1994_2025_Years_Available",
            "GW_1994_2025_Trend"
        ]
    ]
)

# ---------------------------------------------------------
# Combine districts for inspection
# ---------------------------------------------------------

inspect_districts = pd.concat(
    [
        top_long_term,
        bottom_long_term
    ]
).drop_duplicates(
    subset=[
        "State_Standard",
        "District_Standard"
    ]
)

# ---------------------------------------------------------
# Retrieve yearly groundwater values
# ---------------------------------------------------------

inspection = (
    district_year_gw
    .merge(
        inspect_districts[
            [
                "State_Standard",
                "District_Standard"
            ]
        ],
        on=[
            "State_Standard",
            "District_Standard"
        ],
        how="inner"
    )
    [
        [
            "State_Standard",
            "District_Standard",
            "Year",
            "GW_Mean",
            "GW_Median",
            "GW_Min",
            "GW_Max",
            "Station_Count"
        ]
    ]
    .sort_values(
        [
            "State_Standard",
            "District_Standard",
            "Year"
        ]
    )
)

print("=" * 70)
print("EXTREME LONG-TERM TREND INSPECTION")
print("=" * 70)

print(
    "\nNumber of districts inspected:",
    inspect_districts.shape[0]
)

print(
    "\nDistricts selected:"
)

print(
    inspect_districts
    .sort_values(
        "GW_1994_2025_Trend",
        ascending=False
    )
    .to_string(index=False)
)

print(
    "\n" + "=" * 70
)
print(
    "YEARLY VALUES"
)
print("=" * 70)

print(
    inspection
    .to_string(index=False)
)

======================================================================
EXTREME LONG-TERM TREND INSPECTION
======================================================================

Number of districts inspected: 20

Districts selected:
   State_Standard   District_Standard  GW_1994_2025_Years_Available  GW_1994_2025_Trend
      Uttarakhand        Rudra Prayag                             2           21.285000
      Uttarakhand             Chamoli                             2           13.285385
 Himachal Pradesh              Chamba                             2            4.100000
      Uttarakhand         Pithoragarh                             2            3.970182
      Uttarakhand       Tehri Garhwal                             3            3.677000
 Himachal Pradesh            Bilaspur                             2            2.882778
         Nagaland            Tseminyu                             2            2.546000
          Mizoram             Kolasib                             2            2.190000
Jammu And Kashmir              Poonch                             3            2.120000
          Mizoram            Serchhip                             2            1.550000
         Nagaland                Phek                             2           -0.321429
Jammu And Kashmir           Bandipora                             2           -0.393333
        Rajasthan             Jodhpur                            32           -0.435201
         Nagaland               Wokha                             7           -0.516330
        Rajasthan             Bikaner                            32           -0.774319
          Manipur           Kangpokpi                             2           -0.785000
Arunachal Pradesh Lower Dibang Valley                             4           -0.835294
Jammu And Kashmir           Ganderbal                             3           -1.710000
      Uttarakhand           Bageshwar                             2           -2.253333
      Uttarakhand              Almora                             2           -6.886364

======================================================================
YEARLY VALUES
======================================================================
   State_Standard   District_Standard  Year   GW_Mean  GW_Median  GW_Min  GW_Max  Station_Count
Arunachal Pradesh Lower Dibang Valley  2020 10.600000     10.600   10.60   10.60              1
Arunachal Pradesh Lower Dibang Valley  2021 11.200000     11.200   11.20   11.20              1
Arunachal Pradesh Lower Dibang Valley  2024  2.700000      2.700    2.70    2.70              1
Arunachal Pradesh Lower Dibang Valley  2025 10.020000     10.020   10.02   10.02              1
 Himachal Pradesh            Bilaspur  2024 12.191667      5.800    0.40   65.70             12
 Himachal Pradesh            Bilaspur  2025 15.074444      6.480    0.65   67.65              9
 Himachal Pradesh              Chamba  2024  7.300000      4.100    0.00   17.80              3
 Himachal Pradesh              Chamba  2025 11.400000     11.400    5.24   17.56              2
Jammu And Kashmir           Bandipora  2024  1.800000      2.100    0.90    2.10              4
Jammu And Kashmir           Bandipora  2025  1.406667      1.370    1.10    1.75              3
Jammu And Kashmir           Ganderbal  2023  8.000000      8.000    8.00    8.00              1
Jammu And Kashmir           Ganderbal  2024  6.450000      6.450    1.50   11.40              2
Jammu And Kashmir           Ganderbal  2025  4.580000      4.580    1.98    7.18              2
Jammu And Kashmir              Poonch  2023  9.300000      8.900    4.60   17.20              5
Jammu And Kashmir              Poonch  2024  9.825000      8.850    5.10   16.50              4
Jammu And Kashmir              Poonch  2025 13.540000     13.185    5.84   21.95              4
          Manipur           Kangpokpi  2024  2.900000      2.900    2.20    3.60              2
          Manipur           Kangpokpi  2025  2.115000      2.115    2.07    2.16              2
          Mizoram             Kolasib  2024  0.400000      0.400    0.40    0.40              1
          Mizoram             Kolasib  2025  2.590000      2.590    0.48    4.70              2
          Mizoram            Serchhip  2024  0.000000      0.000    0.00    0.00              1
          Mizoram            Serchhip  2025  1.550000      1.550    0.82    2.28              2
         Nagaland                Phek  2024  3.680000      2.900    1.80    7.20              5
         Nagaland                Phek  2025  3.358571      3.000    0.55    7.34              7
         Nagaland            Tseminyu  2024  7.340000      9.100    2.20   13.10              5
         Nagaland            Tseminyu  2025  9.886000     12.700    2.23   13.93              5
         Nagaland               Wokha  2011  5.090000      5.090    3.04    7.14              2
         Nagaland               Wokha  2013  8.420000      8.420    5.63   11.21              2
         Nagaland               Wokha  2014 15.060000     11.580    5.52   28.08              3
         Nagaland               Wokha  2015 16.140000     11.920    6.25   30.25              3
         Nagaland               Wokha  2016  8.805000      8.805    6.97   10.64              2
         Nagaland               Wokha  2024  2.275000      2.300    1.20    3.30              4
         Nagaland               Wokha  2025  4.205000      4.150    2.41    6.11              4
        Rajasthan             Bikaner  1994 47.249000     42.650   11.20   96.93             50
        Rajasthan             Bikaner  1995 50.373214     45.715    9.68  102.27             56
        Rajasthan             Bikaner  1996 51.664595     44.730   10.25  103.80             37
        Rajasthan             Bikaner  1997 53.241148     48.400    9.10  110.70             61
        Rajasthan             Bikaner  1998 50.874717     47.370   11.56   97.10             53
        Rajasthan             Bikaner  1999 53.659344     49.200   10.80  109.94             61
        Rajasthan             Bikaner  2000 50.690357     46.370   14.06  109.97             56
        Rajasthan             Bikaner  2001 52.682985     47.730   16.05  117.22             67
        Rajasthan             Bikaner  2002 54.225278     50.515   10.70  114.72             72
        Rajasthan             Bikaner  2003 53.393169     49.730   10.52  112.50             71
        Rajasthan             Bikaner  2004 50.156857     44.460   10.97  114.88             70
        Rajasthan             Bikaner  2005 50.882727     46.600    9.74  112.22             66
        Rajasthan             Bikaner  2006 49.199516     43.620    9.59  110.20             62
        Rajasthan             Bikaner  2007 48.057258     44.310    8.64  110.43             62
        Rajasthan             Bikaner  2008 48.676172     43.130    8.90  111.89             64
        Rajasthan             Bikaner  2009 46.870439     39.230    7.27  110.77             57
        Rajasthan             Bikaner  2010 46.786364     37.840    7.39  111.00             55
        Rajasthan             Bikaner  2011 46.101172     39.055    8.54  111.70             64
        Rajasthan             Bikaner  2012 48.816400     39.070    8.49  120.85             50
        Rajasthan             Bikaner  2013 38.985417     32.940   11.75  123.55             24
        Rajasthan             Bikaner  2014 36.024516     31.870    6.89  111.60             31
        Rajasthan             Bikaner  2015 36.877241     32.090    6.89  111.75             29
        Rajasthan             Bikaner  2016 31.632424     31.170    6.27   79.28             33
        Rajasthan             Bikaner  2017 34.513714     32.300    6.55  114.22             35
        Rajasthan             Bikaner  2018 33.233548     29.970    5.30  114.00             31
        Rajasthan             Bikaner  2019 34.875000     30.900    5.10  128.20             40
        Rajasthan             Bikaner  2020 32.232051     28.400    4.20  114.90             39
        Rajasthan             Bikaner  2021 39.060976     29.400    4.70  116.80             41
        Rajasthan             Bikaner  2022 33.797436     29.800    7.50  118.10             39
        Rajasthan             Bikaner  2023 29.819355     24.100    7.00   97.70             31
        Rajasthan             Bikaner  2024 31.724194     27.800    6.30  101.00             31
        Rajasthan             Bikaner  2025 36.886053     32.235    3.50  101.98             38
        Rajasthan             Jodhpur  1994 39.665000     39.665   29.80   49.53              2
        Rajasthan             Jodhpur  1995 26.230000     26.230   26.23   26.23              1
        Rajasthan             Jodhpur  1996 26.060000     26.060   26.06   26.06              1
        Rajasthan             Jodhpur  1997 23.470000     23.470   23.47   23.47              1
        Rajasthan             Jodhpur  1998 19.310000     19.310   19.31   19.31              1
        Rajasthan             Jodhpur  1999 28.095000     28.095   13.88   42.31              2
        Rajasthan             Jodhpur  2000 27.790000     27.790   14.28   41.30              2
        Rajasthan             Jodhpur  2001 24.800000     24.800   10.65   38.95              2
        Rajasthan             Jodhpur  2002 22.055000     22.055    8.12   35.99              2
        Rajasthan             Jodhpur  2003 23.195000     23.195    9.22   37.17              2
        Rajasthan             Jodhpur  2004 37.070000     37.070   37.07   37.07              1
        Rajasthan             Jodhpur  2005 18.010000     10.190    3.85   39.99              3
        Rajasthan             Jodhpur  2006 17.640000      9.190    3.78   39.95              3
        Rajasthan             Jodhpur  2007 15.866667      7.890    3.42   36.29              3
        Rajasthan             Jodhpur  2008 14.756667      8.190    1.79   34.29              3
        Rajasthan             Jodhpur  2009 14.260000      6.290    1.60   34.89              3
        Rajasthan             Jodhpur  2010 20.740000     20.740    8.29   33.19              2
        Rajasthan             Jodhpur  2011 19.105000     19.105    8.19   30.02              2
        Rajasthan             Jodhpur  2012  7.690000      7.690    7.69    7.69              1
        Rajasthan             Jodhpur  2013 16.990000     16.990    7.09   26.89              2
        Rajasthan             Jodhpur  2014 15.950000     15.950    5.74   26.16              2
        Rajasthan             Jodhpur  2015 18.382500     19.710    7.62   26.49              4
        Rajasthan             Jodhpur  2016 20.995000     20.195   17.40   26.19              4
        Rajasthan             Jodhpur  2017 16.832500     17.275    6.89   25.89              4
        Rajasthan             Jodhpur  2018 17.732500     19.375    7.99   24.19              4
        Rajasthan             Jodhpur  2019 17.600000     16.900   11.70   24.20              3
        Rajasthan             Jodhpur  2020 17.225000     19.100    7.00   23.70              4
        Rajasthan             Jodhpur  2021  8.300000      8.300    8.30    8.30              1
        Rajasthan             Jodhpur  2022 18.325000     18.400   10.30   26.20              4
        Rajasthan             Jodhpur  2023 18.175000     18.100    9.40   27.10              4
        Rajasthan             Jodhpur  2024 17.975000     17.750    9.20   27.20              4
        Rajasthan             Jodhpur  2025 18.976667     18.490   14.47   23.97              3
      Uttarakhand              Almora  2024 18.236364     13.300    5.00   57.20             11
      Uttarakhand              Almora  2025 11.350000     11.350   11.35   11.35              1
      Uttarakhand           Bageshwar  2024  8.680000      7.200    3.20   16.60              5
      Uttarakhand           Bageshwar  2025  6.426667      4.160    3.95   11.17              3
      Uttarakhand             Chamoli  2024 12.784615     12.900    2.20   30.50             13
      Uttarakhand             Chamoli  2025 26.070000     26.005    2.37   49.90              4
      Uttarakhand         Pithoragarh  2024 10.781818      7.300    2.10   24.90             11
      Uttarakhand         Pithoragarh  2025 14.752000     20.200    0.25   25.01              5
      Uttarakhand        Rudra Prayag  2024 24.100000     20.000    1.80   52.40              5
      Uttarakhand        Rudra Prayag  2025 45.385000     45.385   34.42   56.35              2
      Uttarakhand       Tehri Garhwal  2023 37.400000     40.600   28.20   42.30              5
      Uttarakhand       Tehri Garhwal  2024 35.123077     36.400    4.70   78.50             13
      Uttarakhand       Tehri Garhwal  2025 44.754000     35.600   27.07   82.30              5

In [51]:
# =========================================================
# STEP 14 — FINAL GROUNDWATER FEATURE TABLE
# =========================================================

gw_final = gw_features[
    [
        "State_Standard",
        "District_Standard",

        # Long-term groundwater condition
        "GW_1994_2025_Mean",
        "GW_1994_2025_Median",
        "GW_1994_2025_Std",
        "GW_1994_2025_Trend",
        "GW_1994_2025_Years_Available",

        # Modeling-period condition
        "GW_2015_2025_Mean",
        "GW_2015_2025_Median",
        "GW_2015_2025_Std",
        "GW_2015_2025_Trend",
        "GW_2015_2025_Years_Available",

        # Recent condition
        "GW_2021_2025_Mean",
        "GW_2021_2025_Median",
        "GW_2021_2025_Std",
        "GW_2021_2025_Trend",
        "GW_2021_2025_Years_Available",

        # Latest condition
        "GW_Latest_2025",
        "GW_Latest_Median_2025",
        "GW_Latest_Std_2025",
        "GW_Stations_2025",

        # Historical change
        "GW_Mean_2015_2019",
        "GW_Mean_2021_2025",
        "GW_Recent_vs_Early_Change"
    ]
].copy()


# ---------------------------------------------------------
# Add explicit coverage indicators
# ---------------------------------------------------------

gw_final["GW_2025_Available"] = (
    gw_final["GW_Latest_2025"]
    .notna()
    .astype(int)
)

gw_final["GW_2015_2025_Coverage_Ratio"] = (
    gw_final["GW_2015_2025_Years_Available"]
    / 11
)

gw_final["GW_2021_2025_Coverage_Ratio"] = (
    gw_final["GW_2021_2025_Years_Available"]
    / 5
)


# ---------------------------------------------------------
# Check duplicates
# ---------------------------------------------------------

duplicates = gw_final.duplicated(
    subset=[
        "State_Standard",
        "District_Standard"
    ]
).sum()


# ---------------------------------------------------------
# Report
# ---------------------------------------------------------

print("=" * 70)
print("FINAL GROUNDWATER FEATURE TABLE")
print("=" * 70)

print(
    "\nShape:",
    gw_final.shape
)

print(
    "\nDuplicate district keys:",
    duplicates
)

print(
    "\nColumns:"
)

print(
    gw_final.columns.tolist()
)

print(
    "\nMissing values:"
)

print(
    gw_final.isna().sum()
)

print(
    "\n2025 availability:"
)

print(
    gw_final[
        "GW_2025_Available"
    ].value_counts()
)

print(
    "\nCoverage ratio — 2015–2025:"
)

print(
    gw_final[
        "GW_2015_2025_Coverage_Ratio"
    ].describe()
)

print(
    "\nFirst 10 rows:"
)

print(
    gw_final
    .head(10)
    .to_string(index=False)
)

======================================================================
FINAL GROUNDWATER FEATURE TABLE
======================================================================

Shape: (717, 27)

Duplicate district keys: 0

Columns:
['State_Standard', 'District_Standard', 'GW_1994_2025_Mean', 'GW_1994_2025_Median', 'GW_1994_2025_Std', 'GW_1994_2025_Trend', 'GW_1994_2025_Years_Available', 'GW_2015_2025_Mean', 'GW_2015_2025_Median', 'GW_2015_2025_Std', 'GW_2015_2025_Trend', 'GW_2015_2025_Years_Available', 'GW_2021_2025_Mean', 'GW_2021_2025_Median', 'GW_2021_2025_Std', 'GW_2021_2025_Trend', 'GW_2021_2025_Years_Available', 'GW_Latest_2025', 'GW_Latest_Median_2025', 'GW_Latest_Std_2025', 'GW_Stations_2025', 'GW_Mean_2015_2019', 'GW_Mean_2021_2025', 'GW_Recent_vs_Early_Change', 'GW_2025_Available', 'GW_2015_2025_Coverage_Ratio', 'GW_2021_2025_Coverage_Ratio']

Missing values:
State_Standard                   0
District_Standard                0
GW_1994_2025_Mean                0
GW_1994_2025_Median              0
GW_1994_2025_Std                 4
GW_1994_2025_Trend               4
GW_1994_2025_Years_Available     0
GW_2015_2025_Mean                5
GW_2015_2025_Median              5
GW_2015_2025_Std                 9
GW_2015_2025_Trend               9
GW_2015_2025_Years_Available     5
GW_2021_2025_Mean                7
GW_2021_2025_Median              7
GW_2021_2025_Std                10
GW_2021_2025_Trend              10
GW_2021_2025_Years_Available     7
GW_Latest_2025                  19
GW_Latest_Median_2025           19
GW_Latest_Std_2025              19
GW_Stations_2025                19
GW_Mean_2015_2019               29
GW_Mean_2021_2025                7
GW_Recent_vs_Early_Change       31
GW_2025_Available                0
GW_2015_2025_Coverage_Ratio      5
GW_2021_2025_Coverage_Ratio      7
dtype: int64

2025 availability:
GW_2025_Available
1    698
0     19
Name: count, dtype: int64

Coverage ratio — 2015–2025:
count    712.000000
mean       0.908197
std        0.164391
min        0.090909
25%        0.909091
50%        1.000000
75%        1.000000
max        1.000000
Name: GW_2015_2025_Coverage_Ratio, dtype: float64

First 10 rows:
             State_Standard           District_Standard  GW_1994_2025_Mean  GW_1994_2025_Median  GW_1994_2025_Std  GW_1994_2025_Trend  GW_1994_2025_Years_Available  GW_2015_2025_Mean  GW_2015_2025_Median  GW_2015_2025_Std  GW_2015_2025_Trend  GW_2015_2025_Years_Available  GW_2021_2025_Mean  GW_2021_2025_Median  GW_2021_2025_Std  GW_2021_2025_Trend  GW_2021_2025_Years_Available  GW_Latest_2025  GW_Latest_Median_2025  GW_Latest_Std_2025  GW_Stations_2025  GW_Mean_2015_2019  GW_Mean_2021_2025  GW_Recent_vs_Early_Change  GW_2025_Available  GW_2015_2025_Coverage_Ratio  GW_2021_2025_Coverage_Ratio
Andaman And Nicobar Islands    North And Middle Andaman           1.936931             1.756087          0.788586           -0.018940                            23           1.832605             1.646667          0.810260           -0.028107                           9.0           1.846118              1.74125          0.973033            0.157447                           4.0        1.187105                  0.965            0.879880              38.0           1.821794           1.846118                   0.024325                  1                     0.818182                          0.8
Andaman And Nicobar Islands              South Andamans           2.150800             1.872917          0.676711           -0.012826                            24           2.106426             1.820000          0.550671           -0.021978                           9.0           2.124466              1.84250          0.557966           -0.010325                           4.0        1.580000                  1.270            1.277163              71.0           2.091994           2.124466                   0.032473                  1                     0.818182                          0.8
             Andhra Pradesh       Alluri Sitharama Raju           6.193789             5.831667          1.073014           -0.079408                            30           5.240808             4.718333          0.845355           -0.114078                           9.0           4.817883              4.28000          1.187833           -0.497710                           4.0        3.158485                  2.970            2.080439              33.0           5.579149           4.817883                  -0.761266                  1                     0.818182                          0.8
             Andhra Pradesh                  Anakapalli           4.735774             4.385667          0.928691           -0.040468                            30           4.204009             3.679444          0.813417            0.001856                           9.0           4.003646              3.50000          0.973795            0.199708                           4.0        3.459583                  3.200            1.916098              24.0           4.364300           4.003646                  -0.360654                  1                     0.818182                          0.8
             Andhra Pradesh               Ananthapuramu           8.552747             7.605000          2.532930           -0.054613                            31           7.906241             6.613500          2.476070            0.242275                          10.0           8.749492              5.63125          3.554729            2.094033                           4.0        9.964038                  6.275           10.370359              26.0           7.692889           8.749492                   1.056603                  1                     0.909091                          0.8
             Andhra Pradesh                   Annamayya          10.350728             8.783125          3.563539           -0.005546                            32          10.067060             8.279091          3.937561            0.349887                          11.0          10.585371              8.54000          3.897242            1.287348                           5.0       12.496081                  8.600            9.970371              37.0          10.162162          10.585371                   0.423210                  1                     1.000000                          1.0
             Andhra Pradesh                     Bapatla           3.572228             3.050484          0.706334           -0.017966                            31           3.462999             2.921500          0.722266           -0.081741                          10.0           3.172979              2.85875          0.603997            0.090380                           4.0        2.806667                  2.535            1.763580              24.0           3.947616           3.172979                  -0.774637                  1                     0.909091                          0.8
             Andhra Pradesh                    Chittoor           9.298007             8.546774          2.893304           -0.029031                            31           8.549177             7.071000          3.164480            0.439869                          10.0           9.810537              5.67500          4.886190            3.486505                           4.0       13.334667                  5.600           23.955957              30.0           7.734924           9.810537                   2.075613                  1                     0.909091                          0.8
             Andhra Pradesh Dr. B.R. Ambedkar Konaseema           3.415375             2.759944          0.468873           -0.002317                            30           3.522127             2.663333          0.433552            0.024835                           9.0           3.554864              2.53500          0.646351            0.212462                           4.0        3.322581                  2.340            4.269641              31.0           3.495937           3.554864                   0.058927                  1                     0.818182                          0.8
             Andhra Pradesh               East Godavari           6.975012             4.632258          1.996153           -0.087808                            31           5.580493             3.714000          1.438086           -0.093174                          10.0           5.100096              3.28000          1.651444           -0.669193                           4.0        4.773409                  2.520            6.868057              22.0           5.690909           5.100096                  -0.590813                  1                     0.909091                          0.8

In [52]:
# Save final feature table to CSV
gw_final.to_csv("../clean/groundwater_features_final.csv", index=False)